PI2025- Bridge: NetworkPlayer Class Reference
NetworkPlayer Class Reference
Klasa zarządzająca stanem gracza w sieci (Mirror). Zajmuje się wysyłaniem komend (Cmd), odbiorem danych i synchronizacją UI.
Public Member Functions
override void OnStartServer ()
override void OnStartClient ()
void CmdPlayCard (string cardID)
void CmdSubmitBid (BiddingData bid)
void TargetStartBidding (NetworkConnection target, string currentHighestBid)
void CmdRestartMatch ()
void TargetShowHand (NetworkConnection target, string[] hand)
void TargetShowOpponents (NetworkConnection target, int localPlayerIndex)
void TargetUpdatePlayerHand (NetworkConnection target, string[] hand)
Public Attributes
int playerIndex
MultiplayerHandDisplay handDisplay
Private Member Functions
IEnumerator DelayedStart (MultiplayerGameManager manager)
void OnPlayerIndexChanged (int oldIndex, int newIndex)
Detailed Description
Klasa zarządzająca stanem gracza w sieci (Mirror). Zajmuje się wysyłaniem komend (Cmd), odbiorem danych i synchronizacją UI.
Definition at line 10 of file NetworkPlayer.cs.
Member Function Documentation
CmdPlayCard()
void NetworkPlayer.CmdPlayCard (string cardID) inline
Definition at line 74 of file NetworkPlayer.cs.
    {
        MultiplayerGameManager.Instance.CmdPlayCard(cardID, connectionToClient);
    }
References MultiplayerGameManager.CmdPlayCard(), and MultiplayerGameManager.Instance.
CmdRestartMatch()
void NetworkPlayer.CmdRestartMatch () inline
Definition at line 95 of file NetworkPlayer.cs.
    {
        MultiplayerGameManager.Instance.ServerRestartMatch();
    }
References MultiplayerGameManager.Instance, and MultiplayerGameManager.ServerRestartMatch().
CmdSubmitBid()
void NetworkPlayer.CmdSubmitBid (BiddingData bid) inline
Definition at line 80 of file NetworkPlayer.cs.
    {
        MultiplayerGameManager.Instance.ReceiveBidFromPlayer(bid, this);
    }
References MultiplayerGameManager.Instance, and MultiplayerGameManager.ReceiveBidFromPlayer().
DelayedStart()
IEnumerator NetworkPlayer.DelayedStart (MultiplayerGameManager manager) inline private
Definition at line 66 of file NetworkPlayer.cs.
    {
        yield return new WaitForSeconds(0.5f);
        manager.DealCards();
        manager.StartCoroutine(manager.StartBidding());
    }
References MultiplayerGameManager.DealCards(), and MultiplayerGameManager.StartBidding().
Referenced by OnStartServer().
OnPlayerIndexChanged()
void NetworkPlayer.OnPlayerIndexChanged (int oldIndex, int newIndex) inline private
Definition at line 150 of file NetworkPlayer.cs.
    {
        Debug.Log($"[Client] Przypisano playerIndex = {newIndex}");
    }
OnStartClient()
override void NetworkPlayer.OnStartClient () inline
Definition at line 47 of file NetworkPlayer.cs.
    {
        base.OnStartClient();
        if (!isLocalPlayer) return;
        GameObject panel = GameObject.Find("PlayerHand");
        if (panel != null)
        {
            handDisplay = panel.GetComponent<MultiplayerHandDisplay>();
            Debug.Log("Przypisano handDisplay na kliencie");
        }
        else
        {
            Debug.LogWarning("Nie znaleziono PlayerHand w OnStartClient");
        }
        Debug.Log($"[CLIENT] playerIndex={playerIndex},winningBidderIndex={MultiplayerGameManager.Instance.winningBidderIndex}");
    }
References handDisplay.
OnStartServer()
override void NetworkPlayer.OnStartServer () inline
Definition at line 15 of file NetworkPlayer.cs.
    {
        base.OnStartServer();
        if (connectionToClient == null)
        {
            Debug.Log("Pomijam serwerowego NetworkPlayer (ghost, connId: 0)");
            return;
        }
        var manager = MultiplayerGameManager.Instance;
        if (manager == null){
            Debug.LogError("MultiplayerGameManager.Instance == null");
            return;
        }
        if (!MultiplayerGameManager.Instance.players.Contains(this))
        {
            MultiplayerGameManager.Instance.players.Add(this);
            playerIndex = MultiplayerGameManager.Instance.players.Count - 1;
            Debug.Log($"Dodano gracza {playerIndex} (connId: {connectionToClient?.connectionId ?? -1})");
        }
        handDisplay = FindObjectOfType<MultiplayerHandDisplay>();
        //Debug.Log($"NetworkPlayer.StartClient() >> isLocalPlayer: {isLocalPlayer}, connectionId: {connectionToClient?.connectionId ?? -1}");
        if (manager.players.Count == 4)
        {
            Debug.Log("4 gracz dołączony — start gry!");
            for (int i = 0; i < manager.players.Count; i++)
            {
                manager.players[i].playerIndex = i;
            }
            manager.StartCoroutine(DelayedStart(manager));
        }
    }
References DelayedStart(), handDisplay, MultiplayerGameManager.Instance, playerIndex, and MultiplayerGameManager.players.
TargetShowHand()
void NetworkPlayer.TargetShowHand (NetworkConnection target, string[] hand) inline
Definition at line 100 of file NetworkPlayer.cs.
    {
        Debug.Log($"[TargetShowHand] Wywołano dla gracza {playerIndex}, liczba kart: {hand.Length}");
        var panel = GameObject.Find("PlayerHand");
        if (panel == null)
        {
            Debug.LogWarning("Nie znaleziono PlayerHand");
            return;
        }
        var handDisplay = panel.GetComponent<MultiplayerHandDisplay>();
        if (handDisplay != null){
            handDisplay.ClearHand();
            handDisplay.ShowHand(new List<string>(hand), true);
            Debug.Log($"Rodzic: {handDisplay.transform.name}, Child count: {handDisplay.transform.childCount}");
        }
        else
            Debug.LogWarning("Brak komponentu HandDisplay na PlayerHand");
    }
References handDisplay.
Referenced by MultiplayerGameManager.DelayedShowOpponentsForAll().
TargetShowOpponents()
void NetworkPlayer.TargetShowOpponents (NetworkConnection target, int localPlayerIndex) inline
Definition at line 120 of file NetworkPlayer.cs.
    {
        Debug.Log($"[CLIENT] Pokazuję przeciwników, localPlayerIndex = {localPlayerIndex}, dummy= {MultiplayerGameManager.Instance.dummyIndex}");
        int dummyIndex = MultiplayerGameManager.Instance.dummyIndex;
        for (int i = 0; i < 4; i++)
        {
            bool skip = i == localPlayerIndex && i!=MultiplayerGameManager.Instance.dummyIndex;
            if (skip) continue;
            bool isDummy = i== dummyIndex;
            bool faceUp = isDummy;
            Debug.Log($"[Client] Rysuje gracza {i}, faceUp={faceUp}");
            MultiplayerGameManager.Instance.ShowHandForPlayer(i, faceUp);
        }
    }
References MultiplayerGameManager.dummyIndex, MultiplayerGameManager.Instance, and MultiplayerGameManager.ShowHandForPlayer().
TargetStartBidding()
void NetworkPlayer.TargetStartBidding (NetworkConnection target, string currentHighestBid) inline
Definition at line 85 of file NetworkPlayer.cs.
    {
        MultiplayerBiddingUI ui = FindObjectOfType<MultiplayerBiddingUI>();
        if (ui != null)
        {
            ui.ShowBiddingUI(true,currentHighestBid);
            ui.UpdateCurrentBidText("Aktualna: " + (string.IsNullOrEmpty(currentHighestBid) ? "brak" : currentHighestBid));
        }
    }
References MultiplayerBiddingUI.ShowBiddingUI(), and MultiplayerBiddingUI.UpdateCurrentBidText().
Referenced by MultiplayerGameManager.StartBidding().
TargetUpdatePlayerHand()
void NetworkPlayer.TargetUpdatePlayerHand (NetworkConnection target, string[] hand) inline
Definition at line 135 of file NetworkPlayer.cs.
    {
        Debug.Log($"[TargetUpdatePlayerHand] Ręka: {hand.Length} kart");
        var panel = GameObject.Find("PlayerHand");
        var display = panel?.GetComponent<MultiplayerHandDisplay>();
        if (display != null)
        {
            display.ShowHand(new List<string>(hand), true);
        }
        else
        {
            Debug.LogWarning("Brak MultiplayerHandDisplay przy aktualizacji ręki");
        }
    }
Member Data Documentation
handDisplay
MultiplayerHandDisplay NetworkPlayer.handDisplay
Definition at line 14 of file NetworkPlayer.cs.
Referenced by OnStartClient(), OnStartServer(), and TargetShowHand().
playerIndex
int NetworkPlayer.playerIndex
Definition at line 13 of file NetworkPlayer.cs.
Referenced by MultiplayerGameManager.CmdPlayCard(), OnStartServer(), and MultiplayerGameManager.RpcSpawnCardOnTable().
The documentation for this class was generated from the following file:
Assets/Scripts/NetworkPlayer.cs