PI2025- Bridge: MultiplayerGameManager Class Reference
MultiplayerGameManager Class Reference
Główna klasa zarządzająca grą w trybie multiplayer. Odpowiada za rozdawanie kart, rozpoczęcie licytacji i fazy rozgrywki, obsługę tur, punktację i komunikację przez sieć z użyciem Mirror.
Classes
class Bid
class PlayedCard
Public Types
enum PlayerTurn { Bottom , Left , Top , Right }
Public Member Functions
int GetPoints (int teamIndex)
int GetTrickCount ()
List< string > GetLastPlayedCards ()
override void OnStartServer ()
void DealCards ()
Rozdaje wszystkim graczom po 13 kart i synchronizuje je przez sieć.
void RpcForceShowDummy (string[] dummyHand, int dummyIndex)
void ShowHandForPlayer (int handOwnerIndex, bool faceUp, List< string > overrideCards=null)
void CmdPlayCard (string cardID, NetworkConnectionToClient conn)
bool CanPlayCard ()
List< string > GetHandByIndex (int index)
Zwraca aktualną rękę gracza na podstawie jego indeksu.
void ServerRestartMatch ()
void ReceiveBidFromPlayer (BiddingData bid, NetworkPlayer sender)
IEnumerator StartBidding ()
Inicjuje fazę licytacji i zarządza przebiegiem licytacji.
void RefreshOpponentsForAll ()
Public Attributes
List< NetworkPlayer > players = new()
MultiplayerHandDisplay playerHandDisplay
MultiplayerHandDisplay topPlayerHandDisplay
MultiplayerHandDisplay leftPlayerHandDisplay
MultiplayerHandDisplay rightPlayerHandDisplay
GameObject MultiplayerCardPrefab
Transform tablePanel
GameObject endGamePanel
TextMeshProUGUI endGameText
TextMeshProUGUI pointsBelowText
TextMeshProUGUI pointsAboveText
PlayerTurn currentTurn = PlayerTurn.Bottom
List< string > playerHand = new()
List< string > topHand = new()
List< string > leftHand = new()
List< string > rightHand = new()
string leadingSuit = null
List< PlayedCard > currentTrick = new()
int startingPlayerIndex
int currentPlayerIndex
int winningBidderIndex
int dummyIndex
GameObject cardBackPrefab
int highestBidIndex
string[] possibleCalls
List< Bid > biddingHistory = new()
Static Public Attributes
static MultiplayerGameManager Instance
Private Member Functions
void Awake ()
void OnPlayerTurnChanged (int oldIndex, int newIndex)
void RpcReceiveHand (int playerIndex, string[] hand)
List< string > GenerateDeck ()
void Shuffle (List< string > list)
void AdvanceTurn ()
void RpcSpawnCardOnTable (string cardID, int serverPlayerIndex)
void TargetUpdatePlayerHand (NetworkConnection target, string[] hand)
void RpcHighlightCurrentTurn (int playerIndex)
IEnumerator EvaluateTrickWinner ()
Logika wykonywana po zagraniu karty przez gracza. Sprawdza kompletność lewy, aktualizuje stan gry i punktację.
int GetCardValue (string cardID)
void CalculateScore ()
void RpcUpdateScoreUI ()
void EndPlayPhase ()
void RpcClearTable ()
void RpcResetScoreUI ()
void EndGame (int winningTeam)
void RpcAnnounceBid (int bidderIndex, string bidStr)
void ShowOwnHand ()
void StartPlayPhase ()
Rozpoczyna właściwą fazę gry po zakończonej licytacji. Ustawia rozgrywającego, dummy i inicjuje pierwszą turę.
IEnumerator DelayedShowOpponentsForAll ()
IEnumerator DelayedOpponentRefresh ()
IEnumerator DelayedHighlightTurn (int playerIndex)
void RestartGame ()
void RpcRestartGame ()
void ResetForNextDeal ()
void UpdateScoreUI ()
Vector2 GetCardPosition (int playerIndex, int cardIndex)
Private Attributes
int[] tricksWonByPlayer = new int[4]
int[] partsWon = new int[2]
int[] pointsBelowLine = new int[2]
int[] pointsAboveLine = new int[2]
int[] points = new int[2]
bool isEndOfTurn = false
string currentHighestBid = null
string trumpSuit = null
bool biddingInProgress = false
int startingBidderIndex
BiddingData pendingBid = null
int trickNumber
Detailed Description
Główna klasa zarządzająca grą w trybie multiplayer. Odpowiada za rozdawanie kart, rozpoczęcie licytacji i fazy rozgrywki, obsługę tur, punktację i komunikację przez sieć z użyciem Mirror.
Definition at line 14 of file MultiplayerGameManager.cs.
Member Enumeration Documentation
PlayerTurn
enum MultiplayerGameManager.PlayerTurn
Enumerator
Bottom
Left
Top
Right
Definition at line 27 of file MultiplayerGameManager.cs.
{ Bottom, Left, Top, Right }
Member Function Documentation
AdvanceTurn()
void MultiplayerGameManager.AdvanceTurn () inline private
Definition at line 270 of file MultiplayerGameManager.cs.
    {
        isEndOfTurn=false;
        Debug.Log($"[AdvanceTurn] Obecny gracz: {currentPlayerIndex}");
        currentPlayerIndex = (currentPlayerIndex + 1) % 4;
        currentTurn = (PlayerTurn)currentPlayerIndex;
        Debug.Log($"[AdvanceTurn] Następny gracz: {currentPlayerIndex}");
        if (currentTrick.Count >= 4)
        {
            leadingSuit = null;
            isEndOfTurn = true;
            StartCoroutine(EvaluateTrickWinner());
            return;
        }
        RpcHighlightCurrentTurn(currentPlayerIndex);
    }
References currentPlayerIndex, currentTrick, currentTurn, EvaluateTrickWinner(), isEndOfTurn, leadingSuit, and RpcHighlightCurrentTurn().
Referenced by CmdPlayCard().
Awake()
void MultiplayerGameManager.Awake () inline private
Definition at line 75 of file MultiplayerGameManager.cs.
    {
        if (Instance == null)
            Instance = this;
        else
            Destroy(gameObject);
    }
References Instance.
CalculateScore()
void MultiplayerGameManager.CalculateScore () inline private
Definition at line 463 of file MultiplayerGameManager.cs.
    {
        int winningTeam = winningBidderIndex % 2;
        int level = int.Parse(currentHighestBid.Substring(0, 1));
        int requiredTricks = level + 6;
        int tricksTaken = 0;
        string suit = currentHighestBid.Substring(1).ToUpper();
        for (int i = 0; i < 4; i++)
            if (i % 2 == winningTeam) tricksTaken += tricksWonByPlayer[i];
        if (tricksTaken >= requiredTricks)
        {
            int score = suit switch
            {
                "C" or "D" => 20 * level,
                "H" or "S" => 30 * level,
                "NT" => 40 + 30 * (level - 1),
                _ => 0
            };
            pointsBelowLine[winningTeam] += score;
            int overtricks = tricksTaken - requiredTricks;
            int overtrickPoints = (suit == "C" || suit == "D") ? 20 * overtricks : 30 * overtricks;
            pointsAboveLine[winningTeam] += overtrickPoints;
            if (level == 6) pointsAboveLine[winningTeam] += 500;
            if (level == 7) pointsAboveLine[winningTeam] += 1000;
        }
        else
        {
            int down = requiredTricks - tricksTaken;
            int penalty = down * 50;
            pointsAboveLine[1 - winningTeam] += penalty;
        }
        RpcUpdateScoreUI();
        if (pointsBelowLine[winningTeam] >= 100)
        {
            partsWon[winningTeam]++;
            if (partsWon[winningTeam] >= 2)
            {
                points[0] = pointsBelowLine[0] + pointsAboveLine[0];
                points[1] = pointsBelowLine[1] + pointsAboveLine[1];
                points[winningTeam] += partsWon[1 - winningTeam] == 0 ? 750 : 500;
                int winner = points[0] > points[1] ? 0 : 1;
                EndGame(winner);
                return;
            }
            pointsAboveLine[0] += pointsBelowLine[0];
            pointsAboveLine[1] += pointsBelowLine[1];
            pointsBelowLine[0] = 0;
            pointsBelowLine[1] = 0;
        }
        EndPlayPhase();
    }
References currentHighestBid, EndGame(), EndPlayPhase(), partsWon, points, pointsAboveLine, pointsBelowLine, RpcUpdateScoreUI(), tricksWonByPlayer, and winningBidderIndex.
Referenced by EvaluateTrickWinner().
CanPlayCard()
bool MultiplayerGameManager.CanPlayCard () inline
Definition at line 353 of file MultiplayerGameManager.cs.
    {
        if(isEndOfTurn){
            return false;
        }
        var identity = NetworkClient.connection?.identity;
        if (identity == null) return false;
        var localPlayer = identity.GetComponent<NetworkPlayer>();
        if (localPlayer == null) return false;
        Debug.Log($"[CanPlayCard] Local playerIndex = {localPlayer.playerIndex}, currentPlayerIndex = {currentPlayerIndex}");
        if (currentPlayerIndex==dummyIndex)
        {
            return localPlayer.playerIndex==winningBidderIndex;
        }
        return localPlayer.playerIndex == currentPlayerIndex;
    }
References currentPlayerIndex, dummyIndex, isEndOfTurn, and winningBidderIndex.
Referenced by MultiplayerCardUI.OnCardClicked().
CmdPlayCard()
void MultiplayerGameManager.CmdPlayCard (string cardID, NetworkConnectionToClient conn) inline
Definition at line 231 of file MultiplayerGameManager.cs.
    {
        Debug.Log($"📥 CmdPlayCard od connId={conn.connectionId}, card: {cardID}");
        var player = conn.identity.GetComponent<NetworkPlayer>();
        int playerIndex = player.playerIndex;
        bool isPlayingOwnTurn = playerIndex == currentPlayerIndex;
        bool isDummyTurn = currentPlayerIndex == dummyIndex && playerIndex == winningBidderIndex;
        if (!isPlayingOwnTurn && !isDummyTurn)
        {
            Debug.LogWarning($"Gracz {playerIndex} próbował zagrać nie w swojej turze.");
            return;
        }
        int actualPlayerIndex = currentPlayerIndex;
        var hand = GetHandByIndex(actualPlayerIndex);
        if (!hand.Contains(cardID)) return;
        if (string.IsNullOrEmpty(leadingSuit))
            leadingSuit = cardID.Substring(0, 1);
        if(!string.IsNullOrEmpty(leadingSuit)){
            bool hasLeadingSuit= hand.Exists(card => card.StartsWith(leadingSuit));
            if(hasLeadingSuit && cardID.Substring(0,1)!=leadingSuit){
                return;
            }
        }
        hand.Remove(cardID);
        currentTrick.Add(new PlayedCard(cardID, actualPlayerIndex));
        RpcSpawnCardOnTable(cardID, actualPlayerIndex);
        if(actualPlayerIndex == dummyIndex){
            MultiplayerGameManager.Instance.RefreshOpponentsForAll();
        }else{
            player.TargetUpdatePlayerHand(conn, hand.ToArray());
        }
        Debug.Log($"[CmdPlayCard] Wywołuję AdvanceTurn z currentPlayerIndex={currentPlayerIndex}");
        AdvanceTurn();
    }
References AdvanceTurn(), currentPlayerIndex, currentTrick, dummyIndex, GetHandByIndex(), Instance, leadingSuit, NetworkPlayer.playerIndex, RefreshOpponentsForAll(), RpcSpawnCardOnTable(), and winningBidderIndex.
Referenced by NetworkPlayer.CmdPlayCard(), and MultiplayerCardUI.OnCardClicked().
DealCards()
void MultiplayerGameManager.DealCards () inline
Rozdaje wszystkim graczom po 13 kart i synchronizuje je przez sieć.
Definition at line 102 of file MultiplayerGameManager.cs.
    {
        List<string> deck = GenerateDeck();
        Shuffle(deck);
        playerHand = deck.GetRange(0, 13);
        leftHand = deck.GetRange(13, 13);
        topHand = deck.GetRange(26, 13);
        rightHand = deck.GetRange(39, 13);
        Debug.Log("Rozdano wszystkie karty");
        for (int i = 0; i < players.Count; i++)
        {
            var player = players[i];
            var conn = player.connectionToClient;
            var hand = GetHandByIndex(i).ToArray();
            if (conn != null)
            {
                player.TargetShowHand(conn, hand);
                player.TargetShowOpponents(conn, i);
                Debug.Log($"Wysłano rękę do gracza {i}, 13 kart");
            }
            else if (player.isLocalPlayer)
            {
                var handDisplay = GameObject.Find("PlayerHand")?.GetComponent<HandDisplay>();
                if (handDisplay != null)
                {
                    handDisplay.ShowHand(new List<string>(hand), true);
                    players[i].TargetShowOpponents(conn, i);
                    Debug.Log($"(HOST) Pokazano rękę lokalnie dla gracza {i}");
                }
            }
            else
            {
                Debug.LogError($"Brak connectionToClient dla gracza {i}");
            }
        }
    }
References GenerateDeck(), GetHandByIndex(), leftHand, playerHand, players, rightHand, Shuffle(), and topHand.
Referenced by NetworkPlayer.DelayedStart(), EndPlayPhase(), OnStartServer(), and ResetForNextDeal().
DelayedHighlightTurn()
IEnumerator MultiplayerGameManager.DelayedHighlightTurn (int playerIndex) inline private
Definition at line 731 of file MultiplayerGameManager.cs.
    {
        yield return new WaitForSeconds(0.3f);
        RpcHighlightCurrentTurn(playerIndex);
    }
References RpcHighlightCurrentTurn().
Referenced by StartPlayPhase().
DelayedOpponentRefresh()
IEnumerator MultiplayerGameManager.DelayedOpponentRefresh () inline private
Definition at line 719 of file MultiplayerGameManager.cs.
    {
        yield return new WaitForSeconds(0.25f); // pozwól na SyncVar
        foreach (var p in players)
        {
            if (p.connectionToClient != null)
            {
                p.TargetShowOpponents(p.connectionToClient, p.playerIndex);
            }
        }
    }
References players.
Referenced by RefreshOpponentsForAll().
DelayedShowOpponentsForAll()
IEnumerator MultiplayerGameManager.DelayedShowOpponentsForAll () inline private
Definition at line 699 of file MultiplayerGameManager.cs.
    {
        yield return new WaitForSeconds(0.5f);
        foreach (var kvp in NetworkServer.connections)
        {
            NetworkConnectionToClient conn = kvp.Value;
            if(conn.identity != null)
            {
                var np=conn.identity.GetComponent<NetworkPlayer>();
                var hand= GetHandByIndex(np.playerIndex).ToArray();
                np.TargetShowHand(conn, hand);
                np.TargetShowOpponents(conn, np.playerIndex);
            }
        }
    }
References GetHandByIndex(), and NetworkPlayer.TargetShowHand().
Referenced by StartPlayPhase().
EndGame()
void MultiplayerGameManager.EndGame (int winningTeam) inline private
Definition at line 560 of file MultiplayerGameManager.cs.
    {
        endGamePanel.SetActive(true);
        endGameText.text = $"Team {(winningTeam == 0 ? "NS" : "EW")} won!";
    }
References endGamePanel.
Referenced by CalculateScore().
EndPlayPhase()
void MultiplayerGameManager.EndPlayPhase () inline private
Definition at line 524 of file MultiplayerGameManager.cs.
    {
        RpcClearTable();
        trickNumber = 0;
        currentTrick.Clear();
        for (int i = 0; i < 4; i++) tricksWonByPlayer[i] = 0;
        startingBidderIndex = (startingBidderIndex + 1) % 4;
        DealCards();
        StartCoroutine(StartBidding());
    }
References currentTrick, DealCards(), RpcClearTable(), StartBidding(), startingBidderIndex, trickNumber, and tricksWonByPlayer.
Referenced by CalculateScore().
EvaluateTrickWinner()
IEnumerator MultiplayerGameManager.EvaluateTrickWinner () inline private
Logika wykonywana po zagraniu karty przez gracza. Sprawdza kompletność lewy, aktualizuje stan gry i punktację.
Definition at line 391 of file MultiplayerGameManager.cs.
    {
        yield return new WaitForSeconds(1.5f); // krótka pauza zanim ocenisz lewę
        while (currentTrick.Count < 4)
        {
            Debug.Log("Nie można ocenić lewy — liczba kart != 4.");
            yield return null;
        }
        string leadSuit = currentTrick[0].cardID.Substring(0, 1);
        PlayedCard winningCard = currentTrick[0];
        int highestValue = GetCardValue(winningCard.cardID);
        string winningSuit = leadSuit;
        foreach (var played in currentTrick)
        {
            string suit = played.cardID.Substring(0, 1);
            int value = GetCardValue(played.cardID);
            bool isTrump = (trumpSuit != null && suit == trumpSuit);
            bool winningIsTrump = (trumpSuit != null && winningSuit == trumpSuit);
            if (isTrump && !winningIsTrump)
            {
                winningCard = played;
                highestValue = value;
                winningSuit = suit;
            }
            else if (suit == winningSuit && value > highestValue)
            {
                winningCard = played;
                highestValue = value;
            }
        }
        RpcClearTable();
        Debug.Log($"Lewę wygrywa gracz {winningCard.playerIndex}");
        tricksWonByPlayer[winningCard.playerIndex]++;
        currentTrick.Clear();
        leadingSuit = null;
        currentPlayerIndex = winningCard.playerIndex;
        currentTurn = (PlayerTurn)currentPlayerIndex;
        RpcHighlightCurrentTurn(currentPlayerIndex);
        isEndOfTurn = false;
        if (++trickNumber >= 13)
        {
            CalculateScore();
        }
    }
References CalculateScore(), MultiplayerGameManager.PlayedCard.cardID, currentPlayerIndex, currentTrick, currentTurn, GetCardValue(), isEndOfTurn, leadingSuit, RpcClearTable(), RpcHighlightCurrentTurn(), trickNumber, tricksWonByPlayer, and trumpSuit.
Referenced by AdvanceTurn().
GenerateDeck()
List< string > MultiplayerGameManager.GenerateDeck () inline private
Definition at line 164 of file MultiplayerGameManager.cs.
    {
        string[] suits = { "S", "H", "D", "C" };
        string[] values = { "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A" };
        List<string> deck = new();
        foreach (string suit in suits)
            foreach (string value in values)
                deck.Add(suit + value);
        return deck;
    }
Referenced by DealCards().
GetCardPosition()
Vector2 MultiplayerGameManager.GetCardPosition (int playerIndex, int cardIndex) inline private
Definition at line 769 of file MultiplayerGameManager.cs.
    {
        float spacing = 25f;
        Vector2 basePos;
        switch (playerIndex)
        {
            case 1:
                basePos = new Vector2(-300, 0);
                return basePos + new Vector2(0, cardIndex * spacing);
            case 2:
                basePos = new Vector2(-150 + cardIndex * spacing, 150);
                return basePos;
            case 3:
                basePos = new Vector2(300, 0);
                return basePos + new Vector2(0, cardIndex * spacing);
            default:
                return Vector2.zero;
        }
    }
GetCardValue()
int MultiplayerGameManager.GetCardValue (string cardID) inline private
Definition at line 441 of file MultiplayerGameManager.cs.
    {
        string valuePart = cardID.Substring(1);
        return valuePart switch
        {
            "2" => 2,
            "3" => 3,
            "4" => 4,
            "5" => 5,
            "6" => 6,
            "7" => 7,
            "8" => 8,
            "9" => 9,
            "10" => 10,
            "J" => 11,
            "Q" => 12,
            "K" => 13,
            "A" => 14,
            _ => 0
        };
    }
Referenced by EvaluateTrickWinner().
GetHandByIndex()
List< string > MultiplayerGameManager.GetHandByIndex (int index)
Zwraca aktualną rękę gracza na podstawie jego indeksu.
References leftHand, playerHand, rightHand, and topHand.
Referenced by CmdPlayCard(), DealCards(), DelayedShowOpponentsForAll(), RpcReceiveHand(), ShowHandForPlayer(), ShowOwnHand(), and StartPlayPhase().
GetLastPlayedCards()
List< string > MultiplayerGameManager.GetLastPlayedCards ()
References currentTrick.
GetPoints()
int MultiplayerGameManager.GetPoints (int teamIndex)
References pointsAboveLine, and pointsBelowLine.
GetTrickCount()
int MultiplayerGameManager.GetTrickCount ()
References trickNumber.
OnPlayerTurnChanged()
void MultiplayerGameManager.OnPlayerTurnChanged (int oldIndex, int newIndex) inline private
Definition at line 91 of file MultiplayerGameManager.cs.
{
        Debug.Log($"[SyncVar] currentPlayerIndex changed: {oldIndex} -> {newIndex}");
        currentTurn= (PlayerTurn)newIndex;
        if(isClient){
            RpcHighlightCurrentTurn(newIndex);
        }
    }
References currentTurn, and RpcHighlightCurrentTurn().
OnStartServer()
override void MultiplayerGameManager.OnStartServer () inline
Definition at line 83 of file MultiplayerGameManager.cs.
    {
        base.OnStartServer();
        endGamePanel.SetActive(false);
        playerHandDisplay.LoadCardSprites();
        DealCards();
        StartCoroutine(StartBidding());
    }
References DealCards(), endGamePanel, playerHandDisplay, and StartBidding().
ReceiveBidFromPlayer()
void MultiplayerGameManager.ReceiveBidFromPlayer (BiddingData bid, NetworkPlayer sender) inline
Definition at line 573 of file MultiplayerGameManager.cs.
    {
        int bidderIndex = players.IndexOf(sender);
        if (bidderIndex != currentPlayerIndex) return;
        string bidStr = bid.ToString();
        biddingHistory.Add(new Bid("Gracz " + bidderIndex, bidStr));
        RpcAnnounceBid(bidderIndex, bidStr);
        int bidIndex = System.Array.IndexOf(possibleCalls, bidStr);
        if (bidStr != "Pas" && bidIndex > highestBidIndex)
        {
            highestBidIndex = bidIndex;
            currentHighestBid = bidStr;
            winningBidderIndex = bidderIndex;
        }
        pendingBid = bid;
    }
References biddingHistory, currentHighestBid, currentPlayerIndex, highestBidIndex, pendingBid, players, possibleCalls, RpcAnnounceBid(), BiddingData.ToString(), and winningBidderIndex.
Referenced by NetworkPlayer.CmdSubmitBid().
RefreshOpponentsForAll()
void MultiplayerGameManager.RefreshOpponentsForAll () inline
Definition at line 714 of file MultiplayerGameManager.cs.
    {
        StartCoroutine(DelayedOpponentRefresh());
    }
References DelayedOpponentRefresh().
Referenced by CmdPlayCard().
ResetForNextDeal()
void MultiplayerGameManager.ResetForNextDeal () inline private
Definition at line 745 of file MultiplayerGameManager.cs.
    {
        Debug.Log("Nowe rozdanie...");
        DealCards();
        biddingHistory.Clear();
        currentHighestBid = null;
        highestBidIndex = -1;
        currentTrick.Clear();
        trickNumber = 0;
        tricksWonByPlayer = new int[4];
        StartCoroutine(StartBidding());
    }
References biddingHistory, currentHighestBid, currentTrick, DealCards(), highestBidIndex, StartBidding(), trickNumber, and tricksWonByPlayer.
Referenced by ServerRestartMatch().
RestartGame()
void MultiplayerGameManager.RestartGame () inline private
Definition at line 736 of file MultiplayerGameManager.cs.
    {
        Debug.Log("RestartGame wywołane — czyszczenie danych");
    }
Referenced by ServerRestartMatch().
RpcAnnounceBid()
void MultiplayerGameManager.RpcAnnounceBid (int bidderIndex, string bidStr) inline private
Definition at line 593 of file MultiplayerGameManager.cs.
    {
        MultiplayerBiddingUI ui = FindObjectOfType<MultiplayerBiddingUI>();
        if (ui != null)
            ui.UpdateCurrentBidText($"Gracz {bidderIndex}: {bidStr}");
    }
References MultiplayerBiddingUI.UpdateCurrentBidText().
Referenced by ReceiveBidFromPlayer().
RpcClearTable()
void MultiplayerGameManager.RpcClearTable () inline private
Definition at line 535 of file MultiplayerGameManager.cs.
    {
        foreach (Transform child in tablePanel)
            Destroy(child.gameObject);
    }
References tablePanel.
Referenced by EndPlayPhase(), and EvaluateTrickWinner().
RpcForceShowDummy()
void MultiplayerGameManager.RpcForceShowDummy (string[] dummyHand, int dummyIndex) inline
Definition at line 157 of file MultiplayerGameManager.cs.
    {
        Debug.Log($"[CLIENT RPC] Recznie pokazuje dummy {dummyIndex} - {dummyHand.Length} kart");
        var localPlayer = NetworkClient.connection.identity.GetComponent<NetworkPlayer>();
        MultiplayerGameManager.Instance.ShowHandForPlayer(dummyIndex, true, dummyHand.ToList());
    }
References dummyIndex, Instance, and ShowHandForPlayer().
Referenced by StartPlayPhase().
RpcHighlightCurrentTurn()
void MultiplayerGameManager.RpcHighlightCurrentTurn (int playerIndex) inline private
Definition at line 348 of file MultiplayerGameManager.cs.
    {
        Debug.Log("Teraz gra gracz: " + playerIndex);
    }
Referenced by AdvanceTurn(), DelayedHighlightTurn(), EvaluateTrickWinner(), and OnPlayerTurnChanged().
RpcReceiveHand()
void MultiplayerGameManager.RpcReceiveHand (int playerIndex, string[] hand) inline private
Definition at line 144 of file MultiplayerGameManager.cs.
    {
        GetHandByIndex(playerIndex).Clear();
        GetHandByIndex(playerIndex).AddRange(hand);
        switch (playerIndex)
        {
            case 0: playerHandDisplay.ShowHand(hand.ToList(), true); break;
            case 1: leftPlayerHandDisplay.ShowHand(hand.ToList(), false); break;
            case 2: topPlayerHandDisplay.ShowHand(hand.ToList(), false); break;
            case 3: rightPlayerHandDisplay.ShowHand(hand.ToList(), false); break;
        }
    }
References GetHandByIndex(), leftPlayerHandDisplay, playerHandDisplay, rightPlayerHandDisplay, and topPlayerHandDisplay.
RpcResetScoreUI()
void MultiplayerGameManager.RpcResetScoreUI () inline private
Definition at line 554 of file MultiplayerGameManager.cs.
    {
        pointsBelowText.text = "NS: 0   EW: 0";
        pointsAboveText.text = "NS: 0   EW: 0";
    }
RpcRestartGame()
void MultiplayerGameManager.RpcRestartGame () inline private
Definition at line 741 of file MultiplayerGameManager.cs.
    {
        UpdateScoreUI();
    }
References UpdateScoreUI().
Referenced by ServerRestartMatch().
RpcSpawnCardOnTable()
void MultiplayerGameManager.RpcSpawnCardOnTable (string cardID, int serverPlayerIndex) inline private
Definition at line 287 of file MultiplayerGameManager.cs.
    {
        Debug.Log($"[RpcSpawnCardOnTable] Gracz {serverPlayerIndex} zagrał {cardID}");
        GameObject card = Instantiate(MultiplayerCardPrefab, tablePanel);
        var ui= card.GetComponent<MultiplayerCardUI>();
        ui.cardID= cardID;
        var localPlayer = NetworkClient.connection?.identity?.GetComponent<NetworkPlayer>();
        int localIndex = localPlayer != null ? localPlayer.playerIndex:-1;
        int relativeIndex = (serverPlayerIndex - localIndex + 4) % 4;
        Vector2 pos = relativeIndex switch
        {
            0 => new Vector2(-35, -70),
            1 => new Vector2(-250, 0),
            2 => new Vector2(-35, 70),
            3 => new Vector2(200, 0),
            _ => Vector2.zero
        };
        bool isDummyCard= serverPlayerIndex==dummyIndex;
        bool isWinningPlayer= localIndex==winningBidderIndex;
        if((serverPlayerIndex==localIndex)||(isDummyCard && isWinningPlayer))
        {
            card.GetComponent<Button>().onClick.AddListener(ui.OnCardClicked);
        }
        var allDisplays = FindObjectsOfType<MultiplayerHandDisplay>();
        Dictionary<string, Sprite> spriteDict = null;
        foreach (var d in allDisplays)
        {
            if(d.cardSpriteDict.Count>0){
                spriteDict = d.cardSpriteDict;
                break;
            }
        }
        if (spriteDict.TryGetValue(cardID, out Sprite sprite))
        {
            card.GetComponent<Image>().sprite = sprite;
        }
        else
        {
            Debug.LogWarning($"Nie znaleziono sprite'a dla {cardID}");
        }
        card.GetComponent<RectTransform>().anchoredPosition = pos;
    }
References MultiplayerCardUI.cardID, dummyIndex, MultiplayerCardPrefab, NetworkPlayer.playerIndex, tablePanel, and winningBidderIndex.
Referenced by CmdPlayCard().
RpcUpdateScoreUI()
void MultiplayerGameManager.RpcUpdateScoreUI () inline private
Definition at line 518 of file MultiplayerGameManager.cs.
    {
        if (pointsBelowText != null) pointsBelowText.text = $"NS: {pointsBelowLine[0]}   EW: {pointsBelowLine[1]}";
        if (pointsAboveText != null) pointsAboveText.text = $"NS: {pointsAboveLine[0]}  EW: {pointsAboveLine[1]}";
    }
References pointsAboveText, and pointsBelowText.
Referenced by CalculateScore().
ServerRestartMatch()
void MultiplayerGameManager.ServerRestartMatch () inline
Definition at line 541 of file MultiplayerGameManager.cs.
    {
        endGamePanel.SetActive(false);
        points = new int[2];
        pointsAboveLine = new int[2];
        pointsBelowLine = new int[2];
        partsWon = new int[2];
        RestartGame();
        RpcRestartGame();
        ResetForNextDeal();
    }
References endGamePanel, partsWon, points, pointsAboveLine, pointsBelowLine, ResetForNextDeal(), RestartGame(), and RpcRestartGame().
Referenced by NetworkPlayer.CmdRestartMatch().
ShowHandForPlayer()
void MultiplayerGameManager.ShowHandForPlayer (int handOwnerIndex, bool faceUp, List< string > overrideCards = null) inline
Definition at line 184 of file MultiplayerGameManager.cs.
    {
        Debug.Log($"Show hand for player {handOwnerIndex}, {faceUp}");
        var localPlayer = NetworkClient.connection.identity.GetComponent<NetworkPlayer>();
        if(localPlayer == null) return;
        int relativeIndex = (handOwnerIndex - localPlayer.playerIndex + 4) %4;
        string panelName = relativeIndex switch
        {
            0=>"PlayerHand",
            1=>"LeftHand",
            2=>"TopHand",
            3=>"RightHand",
            _ => null
        };
        var panel = GameObject.Find(panelName);
        if(panel==null){
            Debug.Log($"Nie znaleziono panelu {panelName}");
            return;
        }
        var display = panel.GetComponent<MultiplayerHandDisplay>();
        if(display == null){
            Debug.Log($"Panel {panelName} nie ma multiplayerhanddisplay");
            return;
        }
        List<string> cards;
        if(overrideCards != null)
        {
            cards = overrideCards;
        }
        else if(faceUp)
        {
            var possibleHand = GetHandByIndex(handOwnerIndex);
            if(possibleHand == null || possibleHand.Count == 0)
            {
                Debug.Log("Proba pokazania pustej reki gracza");
                return;
            }
            cards = new List<string>(possibleHand);
        }
        else{
            cards= Enumerable.Repeat("BACK", 13).ToList();
        }
        display.ShowHand(cards, faceUp);
    }
References GetHandByIndex(), and MultiplayerHandDisplay.ShowHand().
Referenced by RpcForceShowDummy(), and NetworkPlayer.TargetShowOpponents().
ShowOwnHand()
void MultiplayerGameManager.ShowOwnHand () inline private
Definition at line 657 of file MultiplayerGameManager.cs.
    {
        var connId = NetworkClient.connection.connectionId;
        var player = players.FirstOrDefault(p => p.connectionToClient?.connectionId == connId);
        if (player != null)
        {
            var hand = GetHandByIndex(player.playerIndex).ToArray();
            player.TargetShowHand(player.connectionToClient, hand);
        }
    }
References GetHandByIndex(), and players.
Referenced by StartBidding().
Shuffle()
void MultiplayerGameManager.Shuffle (List< string > list) inline private
Definition at line 175 of file MultiplayerGameManager.cs.
    {
        for (int i = 0; i < list.Count; i++)
        {
            int rnd = Random.Range(i, list.Count);
            (list[i], list[rnd]) = (list[rnd], list[i]);
        }
    }
Referenced by DealCards().
StartBidding()
IEnumerator MultiplayerGameManager.StartBidding () inline
Inicjuje fazę licytacji i zarządza przebiegiem licytacji.
Definition at line 603 of file MultiplayerGameManager.cs.
    {
        Debug.Log("Liczba graczy: " + players.Count);
        if (players.Count < 4)
        {
            Debug.Log("Zbyt mało graczy – licytacja nie może się rozpocząć.");
            yield break;
        }
        biddingInProgress = true;
        int passesInARow = 0;
        int bidderIndex = startingBidderIndex;
        while (biddingInProgress)
        {
            pendingBid = null;
            NetworkPlayer bidder = players[bidderIndex];
            ShowOwnHand();
            if (bidder.connectionToClient == null)
            {
                Debug.Log("Brak connectionToClient u gracza " + bidderIndex);
                yield break;
            }
            bidder.TargetStartBidding(bidder.connectionToClient, currentHighestBid);
            yield return new WaitUntil(() => pendingBid != null);
            string bidStr = pendingBid.ToString();
            if (bidStr == "Pas")
            {
                passesInARow++;
                if (passesInARow >= 3 && !string.IsNullOrEmpty(currentHighestBid))
                {
                    biddingInProgress = false;
                    StartPlayPhase();
                    break;
                }
            }
            else
            {
                passesInARow = 0;
                if (bidStr == "7NT")
                {
                    biddingInProgress = false;
                    winningBidderIndex = bidderIndex;
                    StartPlayPhase();
                    break;
                }
            }
            bidderIndex = (bidderIndex + 1) % players.Count;
            currentPlayerIndex = bidderIndex;
        }
    }
References biddingInProgress, currentHighestBid, currentPlayerIndex, pendingBid, players, ShowOwnHand(), startingBidderIndex, StartPlayPhase(), NetworkPlayer.TargetStartBidding(), and winningBidderIndex.
Referenced by NetworkPlayer.DelayedStart(), EndPlayPhase(), OnStartServer(), and ResetForNextDeal().
StartPlayPhase()
void MultiplayerGameManager.StartPlayPhase () inline private
Rozpoczyna właściwą fazę gry po zakończonej licytacji. Ustawia rozgrywającego, dummy i inicjuje pierwszą turę.
Definition at line 673 of file MultiplayerGameManager.cs.
    {
        isEndOfTurn = false;
        leadingSuit = "";
        trickNumber = 0;
        currentTrick.Clear();
        dummyIndex = (winningBidderIndex + 2) % 4;
        string suitSymbol = currentHighestBid.Substring(1);
        trumpSuit = suitSymbol switch
        {
            "♣"=>"C",
            "♦"=>"D",
            "♥"=>"H",
            "♠"=>"S",
            "NT"=>null,
            _ => null
        };
        currentPlayerIndex = (winningBidderIndex + 1) % 4;
        currentTurn = (PlayerTurn)currentPlayerIndex;
        StartCoroutine(DelayedHighlightTurn(currentPlayerIndex));
        RpcForceShowDummy(GetHandByIndex(dummyIndex).ToArray(), dummyIndex);
        StartCoroutine(DelayedShowOpponentsForAll());
    }
References currentHighestBid, currentPlayerIndex, currentTrick, currentTurn, DelayedHighlightTurn(), DelayedShowOpponentsForAll(), dummyIndex, GetHandByIndex(), isEndOfTurn, leadingSuit, RpcForceShowDummy(), trickNumber, trumpSuit, and winningBidderIndex.
Referenced by StartBidding().
TargetUpdatePlayerHand()
void MultiplayerGameManager.TargetUpdatePlayerHand (NetworkConnection target, string[] hand) inline private
Definition at line 336 of file MultiplayerGameManager.cs.
    {
        Debug.Log($"[TargetUpdatePlayerHand] pokazuję {hand.Length} kart");
        var panel = GameObject.Find("PlayerHand");
        if (panel != null)
        {
            var display = panel.GetComponent<MultiplayerHandDisplay>();
            display.ShowHand(new List<string>(hand), true);
        }
    }
References MultiplayerHandDisplay.ShowHand().
UpdateScoreUI()
void MultiplayerGameManager.UpdateScoreUI () inline private
Definition at line 760 of file MultiplayerGameManager.cs.
    {
        if (pointsBelowText != null)
            pointsBelowText.text = $"NS: {pointsBelowLine[0]}   EW: {pointsBelowLine[1]}";
        if (pointsAboveText != null)
            pointsAboveText.text = $"NS: {pointsAboveLine[0]}   EW: {pointsAboveLine[1]}";
    }
References pointsAboveText, and pointsBelowText.
Referenced by RpcRestartGame().
Member Data Documentation
biddingHistory
List<Bid> MultiplayerGameManager.biddingHistory = new()
Definition at line 802 of file MultiplayerGameManager.cs.
Referenced by ReceiveBidFromPlayer(), and ResetForNextDeal().
biddingInProgress
bool MultiplayerGameManager.biddingInProgress = false private
Definition at line 57 of file MultiplayerGameManager.cs.
Referenced by StartBidding().
cardBackPrefab
GameObject MultiplayerGameManager.cardBackPrefab
Definition at line 52 of file MultiplayerGameManager.cs.
currentHighestBid
string MultiplayerGameManager.currentHighestBid = null private
Definition at line 55 of file MultiplayerGameManager.cs.
Referenced by CalculateScore(), ReceiveBidFromPlayer(), ResetForNextDeal(), StartBidding(), and StartPlayPhase().
currentPlayerIndex
int MultiplayerGameManager.currentPlayerIndex
Definition at line 39 of file MultiplayerGameManager.cs.
Referenced by AdvanceTurn(), CanPlayCard(), CmdPlayCard(), EvaluateTrickWinner(), ReceiveBidFromPlayer(), StartBidding(), and StartPlayPhase().
currentTrick
List<PlayedCard> MultiplayerGameManager.currentTrick = new()
Definition at line 36 of file MultiplayerGameManager.cs.
Referenced by AdvanceTurn(), CmdPlayCard(), EndPlayPhase(), EvaluateTrickWinner(), GetLastPlayedCards(), ResetForNextDeal(), and StartPlayPhase().
currentTurn
PlayerTurn MultiplayerGameManager.currentTurn = PlayerTurn.Bottom
Definition at line 28 of file MultiplayerGameManager.cs.
Referenced by AdvanceTurn(), EvaluateTrickWinner(), OnPlayerTurnChanged(), and StartPlayPhase().
dummyIndex
int MultiplayerGameManager.dummyIndex
Definition at line 51 of file MultiplayerGameManager.cs.
Referenced by CanPlayCard(), CmdPlayCard(), RpcForceShowDummy(), RpcSpawnCardOnTable(), StartPlayPhase(), and NetworkPlayer.TargetShowOpponents().
endGamePanel
GameObject MultiplayerGameManager.endGamePanel
Definition at line 22 of file MultiplayerGameManager.cs.
Referenced by EndGame(), OnStartServer(), and ServerRestartMatch().
endGameText
TextMeshProUGUI MultiplayerGameManager.endGameText
Definition at line 23 of file MultiplayerGameManager.cs.
highestBidIndex
int MultiplayerGameManager.highestBidIndex
Definition at line 54 of file MultiplayerGameManager.cs.
Referenced by ReceiveBidFromPlayer(), and ResetForNextDeal().
Instance
MultiplayerGameManager MultiplayerGameManager.Instance static
Definition at line 16 of file MultiplayerGameManager.cs.
Referenced by Awake(), CmdPlayCard(), NetworkPlayer.CmdPlayCard(), NetworkPlayer.CmdRestartMatch(), NetworkPlayer.CmdSubmitBid(), MultiplayerCardUI.OnCardClicked(), NetworkPlayer.OnStartServer(), RpcForceShowDummy(), NetworkPlayer.TargetShowOpponents(), and MatchStatsUI.UpdateDisplay().
isEndOfTurn
bool MultiplayerGameManager.isEndOfTurn = false private
Definition at line 47 of file MultiplayerGameManager.cs.
Referenced by AdvanceTurn(), CanPlayCard(), EvaluateTrickWinner(), and StartPlayPhase().
leadingSuit
string MultiplayerGameManager.leadingSuit = null
Definition at line 35 of file MultiplayerGameManager.cs.
Referenced by AdvanceTurn(), CmdPlayCard(), EvaluateTrickWinner(), and StartPlayPhase().
leftHand
List<string> MultiplayerGameManager.leftHand = new()
Definition at line 32 of file MultiplayerGameManager.cs.
Referenced by DealCards(), and GetHandByIndex().
leftPlayerHandDisplay
MultiplayerHandDisplay MultiplayerGameManager.leftPlayerHandDisplay
Definition at line 19 of file MultiplayerGameManager.cs.
Referenced by RpcReceiveHand().
MultiplayerCardPrefab
GameObject MultiplayerGameManager.MultiplayerCardPrefab
Definition at line 20 of file MultiplayerGameManager.cs.
Referenced by RpcSpawnCardOnTable().
partsWon
int [] MultiplayerGameManager.partsWon = new int[2] private
Definition at line 42 of file MultiplayerGameManager.cs.
Referenced by CalculateScore(), and ServerRestartMatch().
pendingBid
BiddingData MultiplayerGameManager.pendingBid = null private
Definition at line 59 of file MultiplayerGameManager.cs.
Referenced by ReceiveBidFromPlayer(), and StartBidding().
playerHand
List<string> MultiplayerGameManager.playerHand = new()
Definition at line 30 of file MultiplayerGameManager.cs.
Referenced by DealCards(), and GetHandByIndex().
playerHandDisplay
MultiplayerHandDisplay MultiplayerGameManager.playerHandDisplay
Definition at line 19 of file MultiplayerGameManager.cs.
Referenced by OnStartServer(), and RpcReceiveHand().
players
List<NetworkPlayer> MultiplayerGameManager.players = new()
Definition at line 17 of file MultiplayerGameManager.cs.
Referenced by DealCards(), DelayedOpponentRefresh(), NetworkPlayer.OnStartServer(), ReceiveBidFromPlayer(), ShowOwnHand(), and StartBidding().
points
int [] MultiplayerGameManager.points = new int[2] private
Definition at line 45 of file MultiplayerGameManager.cs.
Referenced by CalculateScore(), and ServerRestartMatch().
pointsAboveLine
int [] MultiplayerGameManager.pointsAboveLine = new int[2] private
Definition at line 44 of file MultiplayerGameManager.cs.
Referenced by CalculateScore(), GetPoints(), and ServerRestartMatch().
pointsAboveText
TextMeshProUGUI MultiplayerGameManager.pointsAboveText
Definition at line 25 of file MultiplayerGameManager.cs.
Referenced by RpcUpdateScoreUI(), and UpdateScoreUI().
pointsBelowLine
int [] MultiplayerGameManager.pointsBelowLine = new int[2] private
Definition at line 43 of file MultiplayerGameManager.cs.
Referenced by CalculateScore(), GetPoints(), and ServerRestartMatch().
pointsBelowText
TextMeshProUGUI MultiplayerGameManager.pointsBelowText
Definition at line 24 of file MultiplayerGameManager.cs.
Referenced by RpcUpdateScoreUI(), and UpdateScoreUI().
possibleCalls
string [] MultiplayerGameManager.possibleCalls
Initial value:
= {
        "1♣", "1♦", "1♥", "1♠", "1NT",
        "2♣", "2♦", "2♥", "2♠", "2NT",
        "3♣", "3♦", "3♥", "3♠", "3NT",
        "4♣", "4♦", "4♥", "4♠", "4NT",
        "5♣", "5♦", "5♥", "5♠", "5NT",
        "6♣", "6♦", "6♥", "6♠", "6NT",
        "7♣", "7♦", "7♥", "7♠", "7NT"
    }
Definition at line 65 of file MultiplayerGameManager.cs.
{
        "1♣", "1♦", "1♥", "1♠", "1NT",
        "2♣", "2♦", "2♥", "2♠", "2NT",
        "3♣", "3♦", "3♥", "3♠", "3NT",
        "4♣", "4♦", "4♥", "4♠", "4NT",
        "5♣", "5♦", "5♥", "5♠", "5NT",
        "6♣", "6♦", "6♥", "6♠", "6NT",
        "7♣", "7♦", "7♥", "7♠", "7NT"
    };
Referenced by ReceiveBidFromPlayer().
rightHand
List<string> MultiplayerGameManager.rightHand = new()
Definition at line 33 of file MultiplayerGameManager.cs.
Referenced by DealCards(), and GetHandByIndex().
rightPlayerHandDisplay
MultiplayerHandDisplay MultiplayerGameManager.rightPlayerHandDisplay
Definition at line 19 of file MultiplayerGameManager.cs.
Referenced by RpcReceiveHand().
startingBidderIndex
int MultiplayerGameManager.startingBidderIndex private
Definition at line 58 of file MultiplayerGameManager.cs.
Referenced by EndPlayPhase(), and StartBidding().
startingPlayerIndex
int MultiplayerGameManager.startingPlayerIndex
Definition at line 37 of file MultiplayerGameManager.cs.
tablePanel
Transform MultiplayerGameManager.tablePanel
Definition at line 21 of file MultiplayerGameManager.cs.
Referenced by RpcClearTable(), and RpcSpawnCardOnTable().
topHand
List<string> MultiplayerGameManager.topHand = new()
Definition at line 31 of file MultiplayerGameManager.cs.
Referenced by DealCards(), and GetHandByIndex().
topPlayerHandDisplay
MultiplayerHandDisplay MultiplayerGameManager.topPlayerHandDisplay
Definition at line 19 of file MultiplayerGameManager.cs.
Referenced by RpcReceiveHand().
trickNumber
int MultiplayerGameManager.trickNumber private
Definition at line 60 of file MultiplayerGameManager.cs.
Referenced by EndPlayPhase(), EvaluateTrickWinner(), GetTrickCount(), ResetForNextDeal(), and StartPlayPhase().
tricksWonByPlayer
int [] MultiplayerGameManager.tricksWonByPlayer = new int[4] private
Definition at line 41 of file MultiplayerGameManager.cs.
Referenced by CalculateScore(), EndPlayPhase(), EvaluateTrickWinner(), and ResetForNextDeal().
trumpSuit
string MultiplayerGameManager.trumpSuit = null private
Definition at line 56 of file MultiplayerGameManager.cs.
Referenced by EvaluateTrickWinner(), and StartPlayPhase().
winningBidderIndex
int MultiplayerGameManager.winningBidderIndex
Definition at line 49 of file MultiplayerGameManager.cs.
Referenced by CalculateScore(), CanPlayCard(), CmdPlayCard(), ReceiveBidFromPlayer(), RpcSpawnCardOnTable(), StartBidding(), and StartPlayPhase().
The documentation for this class was generated from the following file:
Assets/Scripts/MultiplayerGameManager.cs