PI2025- Bridge: Deck Class Reference
Deck Class Reference
Klasa reprezentująca talię kart.
Public Member Functions
Deck ()
Tworzy nową, posortowaną talię 52 kart.
void Shuffle ()
Card Draw ()
Properties
int Count [get]
Private Attributes
List< Card > cards = new()
Detailed Description
Klasa reprezentująca talię kart.
Definition at line 8 of file Deck.cs.
Constructor & Destructor Documentation
Deck()
Deck.Deck () inline
Tworzy nową, posortowaną talię 52 kart.
Definition at line 16 of file Deck.cs.
    {
        foreach (Suit suit in System.Enum.GetValues(typeof(Suit)))
        {
            foreach (Rank rank in System.Enum.GetValues(typeof(Rank)))
            {
                cards.Add(new Card(suit, rank));
            }
        }
    }
References cards.
Member Function Documentation
Draw()
Card Deck.Draw () inline
Definition at line 36 of file Deck.cs.
    {
        if (cards.Count == 0) return null;
        Card card = cards[0];
        cards.RemoveAt(0);
        return card;
    }
References cards.
Referenced by CardDealer.Start().
Shuffle()
void Deck.Shuffle () inline
Definition at line 27 of file Deck.cs.
    {
        for (int i = 0; i < cards.Count; i++)
        {
            int rnd = Random.Range(i, cards.Count);
            (cards[i], cards[rnd]) = (cards[rnd], cards[i]);
        }
    }
References cards.
Referenced by CardDealer.Start().
Member Data Documentation
cards
List<Card> Deck.cards = new() private
Definition at line 10 of file Deck.cs.
Referenced by Deck(), Draw(), and Shuffle().
Property Documentation
Count
int Deck.Count get
Definition at line 44 of file Deck.cs.
The documentation for this class was generated from the following file:
Assets/Scripts/Deck.cs