PI2025- Bridge: HandDisplay Class Reference
HandDisplay Class Reference
Odpowiada za wyświetlanie kart na ręce gracza oraz AI.
Public Member Functions
void ShowHand (List< string > cards, bool isPlayer)
Wyświetla podaną rękę kart.
void LoadCardSprites ()
Ładuje sprite'y kart z zasobów do słownika.
void ShowDummyHand (List< string > hand)
Public Attributes
Transform handPanel
GameObject cardPrefab
Sprite cardBackSprite
Transform tablePanel
Transform dummyHandPanel
Dictionary< string, Sprite > cardSpriteDict = new Dictionary<string, Sprite>()
Private Member Functions
void Awake ()
Detailed Description
Odpowiada za wyświetlanie kart na ręce gracza oraz AI.
Definition at line 11 of file HandDisplay.cs.
Member Function Documentation
Awake()
void HandDisplay.Awake () inline private
Definition at line 21 of file HandDisplay.cs.
    {
        Sprite[] loadedSprites = Resources.LoadAll<Sprite>("Cards");
        foreach (var sprite in loadedSprites)
        {
            cardSpriteDict[sprite.name] = sprite;
        }
    }
References cardSpriteDict.
LoadCardSprites()
void HandDisplay.LoadCardSprites () inline
Ładuje sprite'y kart z zasobów do słownika.
Definition at line 126 of file HandDisplay.cs.
    {
        Sprite[] sprites = Resources.LoadAll<Sprite>("Cards");
        foreach (Sprite sprite in sprites)
        {
            cardSpriteDict[sprite.name] = sprite;
        }
    }
References cardSpriteDict.
ShowDummyHand()
void HandDisplay.ShowDummyHand (List< string > hand) inline
Definition at line 136 of file HandDisplay.cs.
    {
        foreach (Transform child in dummyHandPanel)
        {
            Destroy(child.gameObject);
        }
        foreach (var cardID in hand)
        {
            GameObject card = Instantiate(cardPrefab, dummyHandPanel);
            Image cardImage = card.GetComponent<Image>();
            if (cardSpriteDict.ContainsKey(cardID))
            {
                cardImage.sprite = cardSpriteDict[cardID];
            }
            else
            {
                Debug.LogWarning("Brak sprite'a dla: " + cardID);
            }
        }
    }
References cardPrefab, cardSpriteDict, and dummyHandPanel.
ShowHand()
void HandDisplay.ShowHand (List< string > cards, bool isPlayer) inline
Wyświetla podaną rękę kart.
Zwraca numer porządkowy koloru do sortowania.
Zamienia wartość karty na liczbę do sortowania.
Definition at line 35 of file HandDisplay.cs.
    {
        foreach (Transform child in handPanel)
        {
            Destroy(child.gameObject);
        }
        float offsetX = 27f;
        int index = 0;
        cards.Sort((card1, card2) => {
        char suit1 = card1[0];
        char suit2 = card2[0];
        int suitOrder1 = GetSuitOrder(suit1);
        int suitOrder2 = GetSuitOrder(suit2);
        if (suitOrder1 != suitOrder2)
        {
            return suitOrder1.CompareTo(suitOrder2);
        }
        int value1 = GetCardValue(card1.Substring(1));
        int value2 = GetCardValue(card2.Substring(1));
        return value1.CompareTo(value2);
    });
    int GetSuitOrder(char suit)
    {
        switch (suit)
        {
            case 'C': return 0;
            case 'D': return 1;
            case 'H': return 2;
            case 'S': return 3;
            default: return 4;
        }
    }
    int GetCardValue(string value)
    {
        switch (value)
        {
            case "J": return 11;
            case "Q": return 12;
            case "K": return 13;
            case "A": return 14;
            default: return int.Parse(value);
        }
    }
        foreach (string cardID in cards)
        {
            GameObject card = Instantiate(cardPrefab, handPanel);
            Image image = card.GetComponent<Image>();
            if(isPlayer){
                if (cardSpriteDict.ContainsKey(cardID))
                {
                  image.sprite = cardSpriteDict[cardID];
                }
                else
                {
                    Debug.LogWarning("Brak sprite'a dla karty: " + cardID);
                }
                card.GetComponent<CardUI>().cardID = cardID;
            }
            else{
                image.sprite = cardBackSprite;
            }
            RectTransform rt = card.GetComponent<RectTransform>();
            rt.anchoredPosition = new Vector2(index * offsetX, 0f);
            index++;
        }
    }
References cardBackSprite, cardPrefab, cardSpriteDict, and handPanel.
Referenced by CardUI.OnMouseDown().
Member Data Documentation
cardBackSprite
Sprite HandDisplay.cardBackSprite
Definition at line 15 of file HandDisplay.cs.
Referenced by ShowHand().
cardPrefab
GameObject HandDisplay.cardPrefab
Definition at line 14 of file HandDisplay.cs.
Referenced by ShowDummyHand(), and ShowHand().
cardSpriteDict
Dictionary<string, Sprite> HandDisplay.cardSpriteDict = new Dictionary<string, Sprite>()
Definition at line 19 of file HandDisplay.cs.
Referenced by Awake(), LoadCardSprites(), ShowDummyHand(), and ShowHand().
dummyHandPanel
Transform HandDisplay.dummyHandPanel
Definition at line 17 of file HandDisplay.cs.
Referenced by ShowDummyHand().
handPanel
Transform HandDisplay.handPanel
Definition at line 13 of file HandDisplay.cs.
Referenced by ShowHand().
tablePanel
Transform HandDisplay.tablePanel
Definition at line 16 of file HandDisplay.cs.
The documentation for this class was generated from the following file:
Assets/Scripts/HandDisplay.cs