PI2025- Bridge: MultiplayerHandDisplay Class Reference
MultiplayerHandDisplay Class Reference
Wyświetla rękę gracza w trybie multiplayer. Obsługuje sortowanie, układanie i aktualizację widoku.
Public Member Functions
void LoadCardSprites ()
void ShowHand (List< string > cards, bool isPlayer)
Pokazuje rękę (listę kart jako stringi), odkrytą lub zakrytą.
void ClearHand ()
List< string > GetCurrentCards ()
Public Attributes
GameObject MultiplayerCardPrefab
bool isFaceUp = true
Dictionary< string, Sprite > cardSpriteDict = new()
Sprite backSprite
Private Member Functions
void Awake ()
int GetSuitOrder (char suit)
int GetCardValue (string value)
Private Attributes
List< string > currentCards = new()
Detailed Description
Wyświetla rękę gracza w trybie multiplayer. Obsługuje sortowanie, układanie i aktualizację widoku.
Definition at line 9 of file MultiplayerHandDisplay.cs.
Member Function Documentation
Awake()
void MultiplayerHandDisplay.Awake () inline private
Definition at line 23 of file MultiplayerHandDisplay.cs.
    {
        LoadCardSprites();
    }
References LoadCardSprites().
ClearHand()
void MultiplayerHandDisplay.ClearHand () inline
Definition at line 96 of file MultiplayerHandDisplay.cs.
    {
        foreach (Transform child in transform)
            Destroy(child.gameObject);
        currentCards.Clear();
    }
References currentCards.
GetCardValue()
int MultiplayerHandDisplay.GetCardValue (string value) inline private
Definition at line 120 of file MultiplayerHandDisplay.cs.
    {
        return value switch
        {
            "2" => 2,
            "3" => 3,
            "4" => 4,
            "5" => 5,
            "6" => 6,
            "7" => 7,
            "8" => 8,
            "9" => 9,
            "10" => 10,
            "J" => 11,
            "Q" => 12,
            "K" => 13,
            "A" => 14,
            _ => 0
        };
    }
Referenced by ShowHand().
GetCurrentCards()
List< string > MultiplayerHandDisplay.GetCurrentCards () inline
Definition at line 104 of file MultiplayerHandDisplay.cs.
    {
        return new List<string>(currentCards);
    }
References currentCards.
GetSuitOrder()
int MultiplayerHandDisplay.GetSuitOrder (char suit) inline private
Definition at line 108 of file MultiplayerHandDisplay.cs.
    {
        switch (suit)
        {
            case 'C': return 0; // trefl
            case 'D': return 1; // karo
            case 'H': return 2; // kier
            case 'S': return 3; // pik
            default: return 4;
        }
    }
Referenced by ShowHand().
LoadCardSprites()
void MultiplayerHandDisplay.LoadCardSprites () inline
Definition at line 28 of file MultiplayerHandDisplay.cs.
    {
        Sprite[] sprites = Resources.LoadAll<Sprite>("Cards");
        foreach (Sprite sprite in sprites)
        {
            if (!cardSpriteDict.ContainsKey(sprite.name))
            {
                cardSpriteDict[sprite.name] = sprite;
            }
        }
        Debug.Log($"Załadowano {cardSpriteDict.Count} sprite’ów kart.");
    }
References cardSpriteDict.
Referenced by Awake(), and ShowHand().
ShowHand()
void MultiplayerHandDisplay.ShowHand (List< string > cards, bool isPlayer) inline
Pokazuje rękę (listę kart jako stringi), odkrytą lub zakrytą.
Definition at line 46 of file MultiplayerHandDisplay.cs.
    {
        LoadCardSprites();
        foreach (Transform child in transform)
        {
            Destroy(child.gameObject);
        }
        // sortowanie według koloru i wartości
        cards.Sort((card1, card2) =>
        {
            char suit1 = card1[0];
            char suit2 = card2[0];
            int suitOrder1 = GetSuitOrder(suit1);
            int suitOrder2 = GetSuitOrder(suit2);
            if (suitOrder1 != suitOrder2)
                return suitOrder1.CompareTo(suitOrder2);
            int value1 = GetCardValue(card1.Substring(1));
            int value2 = GetCardValue(card2.Substring(1));
            return value1.CompareTo(value2);
        });
        float offsetX = 27f;
        int index = 0;
        foreach (string cardID in cards)
        {
            GameObject card = Instantiate(MultiplayerCardPrefab, transform);
            RectTransform rect = card.GetComponent<RectTransform>();
            rect.anchoredPosition = new Vector2(index * offsetX, 0);
            var ui = card.GetComponent<MultiplayerCardUI>();
            if (ui != null)
            {
                Sprite sprite = cardID == "BACK"? backSprite : (cardSpriteDict.ContainsKey(cardID) ? cardSpriteDict[cardID] : null);
                ui.InitCard(sprite, cardID);
                ui.SetFaceUp(isPlayer && cardID != "BACK");
                if(sprite == null){
                    Debug.Log($"Nie znaleziono spritea dla {cardID}");
                }
            }
            index++;
        }
    }
References backSprite, cardSpriteDict, GetCardValue(), GetSuitOrder(), LoadCardSprites(), and MultiplayerCardPrefab.
Referenced by MultiplayerGameManager.ShowHandForPlayer(), and MultiplayerGameManager.TargetUpdatePlayerHand().
Member Data Documentation
backSprite
Sprite MultiplayerHandDisplay.backSprite
Definition at line 19 of file MultiplayerHandDisplay.cs.
Referenced by ShowHand().
cardSpriteDict
Dictionary<string, Sprite> MultiplayerHandDisplay.cardSpriteDict = new()
Definition at line 16 of file MultiplayerHandDisplay.cs.
Referenced by LoadCardSprites(), and ShowHand().
currentCards
List<string> MultiplayerHandDisplay.currentCards = new() private
Definition at line 21 of file MultiplayerHandDisplay.cs.
Referenced by ClearHand(), and GetCurrentCards().
isFaceUp
bool MultiplayerHandDisplay.isFaceUp = true
Definition at line 13 of file MultiplayerHandDisplay.cs.
MultiplayerCardPrefab
GameObject MultiplayerHandDisplay.MultiplayerCardPrefab
Definition at line 12 of file MultiplayerHandDisplay.cs.
Referenced by ShowHand().
The documentation for this class was generated from the following file:
Assets/Scripts/MultiplayerHandDisplay.cs