PI2025- Bridge: BiddingData Class Reference
BiddingData Class Reference
Reprezentuje pojedynczą licytację złożoną z poziomu i koloru.
Public Member Functions
override string ToString ()
Zwraca tekstową reprezentację licytacji.
Static Public Member Functions
static BiddingData Pass ()
Tworzy obiekt reprezentujący pas.
static BiddingData FromString (string bid)
Tworzy obiekt BiddingData z ciągu znaków.
Public Attributes
string level
string suit
Detailed Description
Reprezentuje pojedynczą licytację złożoną z poziomu i koloru.
Definition at line 7 of file BiddingData.cs.
Member Function Documentation
FromString()
static BiddingData BiddingData.FromString (string bid) inline static
Tworzy obiekt BiddingData z ciągu znaków.
Parameters
bid Tekst licytacji
Returns
Obiekt BiddingData
Definition at line 33 of file BiddingData.cs.
    {
        if (string.IsNullOrEmpty(bid) || bid == "Pas")
        {
            return Pass();
        }
        string level = bid.Substring(0, 1);
        string suit = bid.Substring(1).ToUpper();
        return new BiddingData { level = level, suit = suit };
    }
References level, Pass(), and suit.
Referenced by MultiplayerBiddingUI.OnBidSelected().
Pass()
static BiddingData BiddingData.Pass () inline static
Tworzy obiekt reprezentujący pas.
Definition at line 23 of file BiddingData.cs.
    {
        return new BiddingData { level = "", suit = "" };
    }
References level, and suit.
Referenced by FromString(), and MultiplayerBiddingUI.OnPassSelected().
ToString()
override string BiddingData.ToString () inline
Zwraca tekstową reprezentację licytacji.
Definition at line 15 of file BiddingData.cs.
    {
        return string.IsNullOrEmpty(level) || string.IsNullOrEmpty(suit) ? "Pas" : level + suit;
    }
References level, and suit.
Referenced by MultiplayerGameManager.ReceiveBidFromPlayer().
Member Data Documentation
level
string BiddingData.level
Definition at line 9 of file BiddingData.cs.
Referenced by FromString(), Pass(), and ToString().
suit
string BiddingData.suit
Definition at line 10 of file BiddingData.cs.
Referenced by FromString(), Pass(), and ToString().
The documentation for this class was generated from the following file:
Assets/Scripts/BiddingData.cs