PI2025- Bridge: LoginManager Class Reference
LoginManager Class Reference
Obsługuje proces logowania poprzez żądanie HTTP POST do skryptu PHP. W razie sukcesu zapisuje dane użytkownika w UserSession.
Public Member Functions
void OnLoginButtonPressed ()
void OnRegisterButtonPressed ()
void ReturnToMainMenu ()
Public Attributes
TMP_InputField usernameField
TMP_InputField passwordField
TMP_Text statusText
Private Member Functions
IEnumerator LoginCoroutine ()
IEnumerator RegisterCoroutine ()
void OnEnable ()
void OnDisable ()
void OnSceneLoaded (Scene scene, LoadSceneMode mode)
Detailed Description
Obsługuje proces logowania poprzez żądanie HTTP POST do skryptu PHP. W razie sukcesu zapisuje dane użytkownika w UserSession.
Definition at line 12 of file LoginManager.cs.
Member Function Documentation
LoginCoroutine()
IEnumerator LoginManager.LoginCoroutine () inline private
Definition at line 23 of file LoginManager.cs.
    {
        string username = usernameField.text;
        string password = passwordField.text;
        WWWForm form = new WWWForm();
        form.AddField("username", username);
        form.AddField("password", password);
        using (UnityWebRequest www = UnityWebRequest.Post("http://192.168.X.X/bridge_login/bridge_login.php", form))
        {
            yield return www.SendWebRequest();
            if (www.result == UnityWebRequest.Result.Success)
            {
                string json= www.downloadHandler.text;
                PlayerData data = JsonUtility.FromJson<PlayerData>(json);
                if (data.status == "success")
                {
                    UserSession.Instance.username= data.username;
                    UserSession.Instance.elo= data.elo;
                    SceneManager.LoadScene("StartScene");
                }
                else
                {
                    statusText.text = "Incorrect username or password";
                }
            }
            else
            {
                statusText.text = "Connection failure " + www.error;
            }
        }
    }
References PlayerData.elo, UserSession.elo, UserSession.Instance, passwordField, PlayerData.status, PlayerData.username, UserSession.username, and usernameField.
Referenced by OnLoginButtonPressed().
OnDisable()
void LoginManager.OnDisable () inline private
Definition at line 112 of file LoginManager.cs.
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
    }
References OnSceneLoaded().
OnEnable()
void LoginManager.OnEnable () inline private
Definition at line 108 of file LoginManager.cs.
    {
        SceneManager.sceneLoaded += OnSceneLoaded;
    }
References OnSceneLoaded().
OnLoginButtonPressed()
void LoginManager.OnLoginButtonPressed () inline
Definition at line 18 of file LoginManager.cs.
    {
        StartCoroutine(LoginCoroutine());
    }
References LoginCoroutine().
OnRegisterButtonPressed()
void LoginManager.OnRegisterButtonPressed () inline
Definition at line 57 of file LoginManager.cs.
    {
        StartCoroutine(RegisterCoroutine());
    }
References RegisterCoroutine().
OnSceneLoaded()
void LoginManager.OnSceneLoaded (Scene scene, LoadSceneMode mode) inline private
Definition at line 116 of file LoginManager.cs.
    {
        if(scene.name == "StartScene")
        {
            Destroy(this.gameObject);
        }
    }
Referenced by OnDisable(), and OnEnable().
RegisterCoroutine()
IEnumerator LoginManager.RegisterCoroutine () inline private
Definition at line 62 of file LoginManager.cs.
    {
        string username = usernameField.text;
        string password = passwordField.text;
        if (username.Length < 3 || password.Length < 3)
        {
            statusText.text = "Zbyt krótka nazwa użytkownika lub hasło.";
            yield break;
        }
        WWWForm form = new WWWForm();
        form.AddField("username", username);
        form.AddField("password", password);
        using (UnityWebRequest www = UnityWebRequest.Post("http://192.168.X.X/bridge_login/register.php", form))
        {
            yield return www.SendWebRequest();
            if (www.result == UnityWebRequest.Result.Success)
            {
                string response = www.downloadHandler.text;
                if (response == "success")
                {
                    statusText.text = "Rejestracja zakończona sukcesem!";
                }
                else if (response == "exists")
                {
                    statusText.text = "Użytkownik już istnieje.";
                }
                else
                {
                    statusText.text = "Błąd rejestracji.";
                }
            }
            else
            {
                statusText.text = "Błąd połączenia: " + www.error;
            }
        }
    }
References passwordField, and usernameField.
Referenced by OnRegisterButtonPressed().
ReturnToMainMenu()
void LoginManager.ReturnToMainMenu () inline
Definition at line 103 of file LoginManager.cs.
    {
        Debug.Log("Kliknieto Main Menu");
        SceneManager.LoadScene("StartScene");
    }
Member Data Documentation
passwordField
TMP_InputField LoginManager.passwordField
Definition at line 15 of file LoginManager.cs.
Referenced by LoginCoroutine(), and RegisterCoroutine().
statusText
TMP_Text LoginManager.statusText
Definition at line 16 of file LoginManager.cs.
usernameField
TMP_InputField LoginManager.usernameField
Definition at line 14 of file LoginManager.cs.
Referenced by LoginCoroutine(), and RegisterCoroutine().
The documentation for this class was generated from the following file:
Assets/Scripts/LoginManager.cs