PI2025- Bridge: MultiplayerBiddingUI Class Reference
MultiplayerBiddingUI Class Reference
Komponent interfejsu użytkownika do licytacji w trybie multiplayer. Obsługuje wyświetlanie możliwych ofert, przyciski i przesyłanie wybranej oferty.
Public Member Functions
void ShowBiddingUI (bool show, string currentBid=null)
void UpdateCurrentBidText (string text)
void OnBidSelected (string bid)
void OnPassSelected ()
Public Attributes
GameObject panel
TMP_Text currentBidText
Transform buttonContainer
GameObject bidButtonPrefab
Private Member Functions
void Start ()
void GenerateButtons ()
List< string > GetAvailableCalls (string currentBid)
Private Attributes
readonly string[] allBids
Detailed Description
Komponent interfejsu użytkownika do licytacji w trybie multiplayer. Obsługuje wyświetlanie możliwych ofert, przyciski i przesyłanie wybranej oferty.
Definition at line 11 of file MultiplayerBiddingUI.cs.
Member Function Documentation
GenerateButtons()
void MultiplayerBiddingUI.GenerateButtons () inline private
Definition at line 35 of file MultiplayerBiddingUI.cs.
    {
        foreach (string bid in allBids)
        {
            GameObject btnObj = Instantiate(bidButtonPrefab, buttonContainer);
            btnObj.GetComponentInChildren<TMP_Text>().text = bid;
            btnObj.GetComponent<Button>().onClick.AddListener(() => OnBidSelected(bid));
        }
        // Dodaj przycisk „Pas” na końcu
        GameObject passBtn = Instantiate(bidButtonPrefab, buttonContainer);
        passBtn.GetComponentInChildren<TMP_Text>().text = "Pas";
        passBtn.GetComponent<Button>().onClick.AddListener(OnPassSelected);
    }
References allBids, bidButtonPrefab, buttonContainer, OnBidSelected(), and OnPassSelected().
Referenced by Start().
GetAvailableCalls()
List< string > MultiplayerBiddingUI.GetAvailableCalls (string currentBid) inline private
Definition at line 96 of file MultiplayerBiddingUI.cs.
    {
        List<string> options = new();
        int currentIndex = System.Array.IndexOf(allBids, currentBid);
        for (int i = currentIndex + 1; i < allBids.Length; i++)
        {
            options.Add(allBids[i]);
        }
        options.Add("Pas");
        return options;
    }
References allBids.
Referenced by ShowBiddingUI().
OnBidSelected()
void MultiplayerBiddingUI.OnBidSelected (string bid) inline
Definition at line 75 of file MultiplayerBiddingUI.cs.
    {
        var player = NetworkClient.connection.identity.GetComponent<NetworkPlayer>();
        if (player != null)
        {
            BiddingData data = BiddingData.FromString(bid);
            player.CmdSubmitBid(data);
            ShowBiddingUI(false);
        }
    }
References BiddingData.FromString(), and ShowBiddingUI().
Referenced by GenerateButtons(), and ShowBiddingUI().
OnPassSelected()
void MultiplayerBiddingUI.OnPassSelected () inline
Definition at line 86 of file MultiplayerBiddingUI.cs.
    {
        var player = NetworkClient.connection.identity.GetComponent<NetworkPlayer>();
        if (player != null)
        {
            player.CmdSubmitBid(BiddingData.Pass());
            ShowBiddingUI(false);
        }
    }
References BiddingData.Pass(), and ShowBiddingUI().
Referenced by GenerateButtons().
ShowBiddingUI()
void MultiplayerBiddingUI.ShowBiddingUI (bool show, string currentBid = null) inline
Definition at line 50 of file MultiplayerBiddingUI.cs.
    {
        panel.SetActive(show);
        foreach (Transform child in buttonContainer)
        {
            Destroy(child.gameObject);
        }
        List<string> validCalls = GetAvailableCalls(currentBid);
        foreach (string call in validCalls)
        {
            GameObject btn = Instantiate(bidButtonPrefab, buttonContainer);
            btn.GetComponentInChildren<TMP_Text>().text = call;
            btn.GetComponent<Button>().onClick.AddListener(() => OnBidSelected(call));
        }
    }
References bidButtonPrefab, buttonContainer, GetAvailableCalls(), OnBidSelected(), and panel.
Referenced by OnBidSelected(), OnPassSelected(), and NetworkPlayer.TargetStartBidding().
Start()
void MultiplayerBiddingUI.Start () inline private
Definition at line 29 of file MultiplayerBiddingUI.cs.
    {
        GenerateButtons();
        panel.SetActive(false);
    }
References GenerateButtons(), and panel.
UpdateCurrentBidText()
void MultiplayerBiddingUI.UpdateCurrentBidText (string text) inline
Definition at line 69 of file MultiplayerBiddingUI.cs.
    {
        if (currentBidText != null)
            currentBidText.text = text;
    }
References currentBidText.
Referenced by MultiplayerGameManager.RpcAnnounceBid(), and NetworkPlayer.TargetStartBidding().
Member Data Documentation
allBids
readonly string [] MultiplayerBiddingUI.allBids private
Initial value:
=
    {
        "1♣", "1♦", "1♥", "1♠", "1NT",
        "2♣", "2♦", "2♥", "2♠", "2NT",
        "3♣", "3♦", "3♥", "3♠", "3NT",
        "4♣", "4♦", "4♥", "4♠", "4NT",
        "5♣", "5♦", "5♥", "5♠", "5NT",
        "6♣", "6♦", "6♥", "6♠", "6NT",
        "7♣", "7♦", "7♥", "7♠", "7NT"
    }
Definition at line 18 of file MultiplayerBiddingUI.cs.
    {
        "1♣", "1♦", "1♥", "1♠", "1NT",
        "2♣", "2♦", "2♥", "2♠", "2NT",
        "3♣", "3♦", "3♥", "3♠", "3NT",
        "4♣", "4♦", "4♥", "4♠", "4NT",
        "5♣", "5♦", "5♥", "5♠", "5NT",
        "6♣", "6♦", "6♥", "6♠", "6NT",
        "7♣", "7♦", "7♥", "7♠", "7NT"
    };
Referenced by GenerateButtons(), and GetAvailableCalls().
bidButtonPrefab
GameObject MultiplayerBiddingUI.bidButtonPrefab
Definition at line 16 of file MultiplayerBiddingUI.cs.
Referenced by GenerateButtons(), and ShowBiddingUI().
buttonContainer
Transform MultiplayerBiddingUI.buttonContainer
Definition at line 15 of file MultiplayerBiddingUI.cs.
Referenced by GenerateButtons(), and ShowBiddingUI().
currentBidText
TMP_Text MultiplayerBiddingUI.currentBidText
Definition at line 14 of file MultiplayerBiddingUI.cs.
Referenced by UpdateCurrentBidText().
panel
GameObject MultiplayerBiddingUI.panel
Definition at line 13 of file MultiplayerBiddingUI.cs.
Referenced by ShowBiddingUI(), and Start().
The documentation for this class was generated from the following file:
Assets/Scripts/MultiplayerBiddingUI.cs