PI2025- Bridge: CardUI Class Reference
CardUI Class Reference
Obsługuje pojedynczą kartę w UI, przypisuje grafikę i reaguje na kliknięcia.
Public Member Functions
void InitCard (Sprite sprite, string id)
Inicjalizuje kartę z odpowiednią grafiką i ID.
void OnCardClicked ()
Wywoływane przy kliknięciu karty. Przekazuje zagranie do GameManagera.
Public Attributes
Image cardImage
Obrazek karty do wyświetlenia.
string cardID
Private Member Functions
void Start ()
void OnMouseDown ()
Detailed Description
Obsługuje pojedynczą kartę w UI, przypisuje grafikę i reaguje na kliknięcia.
Definition at line 8 of file CardUI.cs.
Member Function Documentation
InitCard()
void CardUI.InitCard (Sprite sprite, string id) inline
Inicjalizuje kartę z odpowiednią grafiką i ID.
Parameters
sprite Sprite karty.
id ID karty.
Definition at line 27 of file CardUI.cs.
    {
        cardImage.sprite = sprite;
        cardID = id;
    }
References cardID.
OnCardClicked()
void CardUI.OnCardClicked () inline
Wywoływane przy kliknięciu karty. Przekazuje zagranie do GameManagera.
Definition at line 38 of file CardUI.cs.
    {
        Debug.Log("Zagrano karte: " + cardID);
        Debug.Log("Czy karta dummy? " + GameManager.Instance.players[GameManager.Instance.dummyIndex].hand.Contains(cardID));
        if(GameManager.Instance.CanPlayCard()){
            GameManager.Instance.PlayCard(cardID);
        }
    }
References GameManager.CanPlayCard(), cardID, GameManager.dummyIndex, GameManager.Instance, GameManager.PlayCard(), and GameManager.players.
Referenced by Start().
OnMouseDown()
void CardUI.OnMouseDown () inline private
Definition at line 47 of file CardUI.cs.
    {
        if (!GameManager.Instance.CanPlayCard()){
            return;
        }
        if (GameManager.Instance.leadingSuit == null){
            GameManager.Instance.leadingSuit = cardID.Substring(0, 1);
        }
        transform.SetParent(GameManager.Instance.tablePanel);
        GameManager.Instance.playerHand.Remove(cardID);
        GameManager.Instance.playerHandDisplay.ShowHand(GameManager.Instance.playerHand, true);
        GameManager.Instance.EndTurn();
    }
References GameManager.CanPlayCard(), cardID, GameManager.EndTurn(), GameManager.Instance, GameManager.leadingSuit, GameManager.playerHand, GameManager.playerHandDisplay, HandDisplay.ShowHand(), and GameManager.tablePanel.
Start()
void CardUI.Start () inline private
Definition at line 16 of file CardUI.cs.
    {
        GetComponent<Button>().onClick.AddListener(() => OnCardClicked());
    }
References OnCardClicked().
Member Data Documentation
cardID
string CardUI.cardID
Definition at line 14 of file CardUI.cs.
Referenced by InitCard(), OnCardClicked(), and OnMouseDown().
cardImage
Image CardUI.cardImage
Obrazek karty do wyświetlenia.
Definition at line 13 of file CardUI.cs.
The documentation for this class was generated from the following file:
Assets/Scripts/CardUI.cs