PI2025- Bridge: GameManager Class Reference
GameManager Class Reference
Główny menedżer gry. Zarządza rozgrywką, kolejnością tur, rękami graczy oraz stołem.
Classes
class Bid
class PlayedCard
Klasa reprezentująca zagrane karty i przypisanych do nich graczy.
Public Types
enum PlayerTurn { Bottom , Left , Top , Right }
Public Member Functions
void PlayCard (string cardID)
Gracz zagrywa kartę.
bool CanPlayCard ()
Sprawdza, czy gracz może teraz zagrać kartę (czy jest jego kolej).
void EndTurn ()
Obsługuje zakończenie jednej tury.
void EndBiddingEarly ()
void RestartGame ()
void ReturnToMainMenu ()
Public Attributes
HandDisplay playerHandDisplay
Wyświetlacze rąk gracza i AI.
HandDisplay topPlayerHandDisplay
HandDisplay leftPlayerHandDisplay
HandDisplay rightPlayerHandDisplay
GameObject cardPrefab
Transform tablePanel
GameObject endGamePanel
TextMeshProUGUI endGameText
List< string > playerHand = new List<string>()
Listy kart posiadanych przez graczy.
List< string > topHand = new List<string>()
List< string > leftHand = new List<string>()
List< string > rightHand = new List<string>()
PlayerTurn currentTurn = PlayerTurn.Bottom
string leadingSuit = null
List< PlayedCard > currentTrick = new List<PlayedCard>()
int startingPlayerIndex = 0
int currentPlayerIndex = 0
List< Player > players = new List<Player>()
List< Bid > biddingHistory = new List<Bid>()
string[] possibleCalls
int highestBidIndex = -1
TextMeshProUGUI pointsBelowText
TextMeshProUGUI pointsAboveText
int dummyIndex = -1
Static Public Attributes
static GameManager Instance
Private Member Functions
void Awake ()
void Start ()
void DealCards ()
Tasuje i rozdaje karty graczom.
List< string > GenerateDeck ()
Tworzy nową talię 52 kart.
void Shuffle (List< string > list)
Tasuje listę kart.
IEnumerator PlayAICard ()
AI zagrywa kartę.
string ChooseValidCard (List< string > hand)
Wybiera poprawną kartę do zagrania przez AI, respektując prowadzony kolor.
List< string > GetCurrentAIHand ()
Zwraca rękę AI aktualnie wykonującego ruch.
void SpawnCardOnTable (string cardID, int playerIndex)
Pozwala wystawić kartę na stole.
void UpdateAIHandDisplay ()
void ClearTable ()
Czyści wszystkie karty ze stołu po zakończeniu lewy.
IEnumerator EvaluateTrickWinner ()
int GetCardValue (string cardID)
IEnumerator StartBidding ()
void StartPlayPhase ()
void CalculateScore ()
void UpdateScoreUI ()
List< string > GetPlayableHand ()
void ResetForNextDeal ()
void EndGame (int winningTeam, int winPoints, int losePoints)
Private Attributes
bool isEndOfTurn = false
int winningBidderIndex = -1
int[] partsWon = new int[2]
int trickNumber =0
Ocenia zwycięzcę lewy i przygotowuje następną turę.
string currentHighestBid =null
bool biddingInProgress = false
string trumpSuit = null
int startingBidderIndex = 0
int[] tricksWonByPlayer = new int[4]
int[] pointsBelowLine = new int[2]
int[] pointsAboveLine = new int[2]
int[] points = new int[2]
bool isPlayingDummy = false
Detailed Description
Główny menedżer gry. Zarządza rozgrywką, kolejnością tur, rękami graczy oraz stołem.
Definition at line 12 of file GameManager.cs.
Member Enumeration Documentation
PlayerTurn
enum GameManager.PlayerTurn
Enumerator
Bottom
Left
Top
Right
Definition at line 35 of file GameManager.cs.
{ Bottom, Left, Top, Right }
Member Function Documentation
Awake()
void GameManager.Awake () inline private
Definition at line 48 of file GameManager.cs.
    {
        if (Instance == null)
            Instance = this;
        else
            Destroy(gameObject);
    }
References Instance.
CalculateScore()
void GameManager.CalculateScore () inline private
Definition at line 680 of file GameManager.cs.
    {
        int winningTeam = winningBidderIndex % 2;
        int level = int.Parse(currentHighestBid.Substring(0, 1));
        int requiredTricks = level + 6;
        int tricksTaken = 0;
        string suit = currentHighestBid.Substring(1).ToUpper();
        for (int i = 0; i < 4; i++)
        {
            if (i % 2 == winningTeam)
                tricksTaken += tricksWonByPlayer[i];
        }
        if (tricksTaken >= requiredTricks)
        {
            int score = 0;
            switch (suit)
            {
                case "C":
                case "D":
                    score = 20 * level;
                    break;
                case "H":
                case "S":
                    score = 30 * level;
                    break;
                case "NT":
                    score = 40 + 30 * (level - 1);
                    break;
            }
            pointsBelowLine[winningTeam]+=score;
            int overtricks= tricksTaken- requiredTricks;
            int overtrickPoints=0;
            switch (suit)
            {
                case "C":
                case "D":
                    overtrickPoints = 20 * overtricks;
                    break;
                case "H":
                case "S":
                case "NT":
                    overtrickPoints = 30 * overtricks;
                    break;
            }
            pointsAboveLine[winningTeam]+=overtrickPoints;
            if(level == 6){
                pointsAboveLine[winningTeam]+=500;
            }
            if(level == 7){
                pointsAboveLine[winningTeam]+=1000;
            }
            Debug.Log($"Zespół {winningTeam} zdobywa {score} punktów za kontrakt i {overtrickPoints} za dodatkowe lewy!");
        }
        else
        {
            int down = requiredTricks - tricksTaken;
            int penalty = down * 50;
            pointsAboveLine[1-winningTeam]+=penalty;
            Debug.Log($"Zespół {1 - winningTeam} zdobywa {penalty} punktów za niewykonanie kontraktu.");
        }
        UpdateScoreUI();
        if (pointsBelowLine[winningTeam] >= 100)
        {
            partsWon[winningTeam]++;
            if (partsWon[winningTeam] >= 2)
            {
                points[0]=pointsAboveLine[0]+pointsBelowLine[0];
                points[1]=pointsAboveLine[1]+pointsBelowLine[1];
                if(partsWon[1-winningTeam]==0){
                    points[winningTeam]+=750;
                }else{
                    points[winningTeam]+=500;
                }
                if(points[1-winningTeam]>points[winningTeam]){
                    Debug.Log($"Zespół {1-winningTeam} wygrywa cały mecz z wynikiem {(points[1-winningTeam]-points[winningTeam])/100}");
                    EndGame(1-winningTeam, points[1-winningTeam], points[winningTeam]);
                }else{
                    Debug.Log($"Zespół {winningTeam} wygrywa cały mecz z wynikiem {(points[winningTeam]-points[1-winningTeam])/100}");
                    EndGame(winningTeam, points[winningTeam], points[1-winningTeam]);
                }
                return;
            }
            pointsAboveLine[0] += pointsBelowLine[0];
            pointsAboveLine[1] += pointsBelowLine[1];
            pointsBelowLine[0] = 0;
            pointsBelowLine[1] = 0;
        }
        ResetForNextDeal();
    }
References currentHighestBid, EndGame(), partsWon, points, pointsAboveLine, pointsBelowLine, ResetForNextDeal(), tricksWonByPlayer, UpdateScoreUI(), and winningBidderIndex.
Referenced by EvaluateTrickWinner().
CanPlayCard()
bool GameManager.CanPlayCard () inline
Sprawdza, czy gracz może teraz zagrać kartę (czy jest jego kolej).
Definition at line 207 of file GameManager.cs.
    {
        if (currentPlayerIndex == 0)
            return true;
        if (currentPlayerIndex == dummyIndex && winningBidderIndex == 0)
            return true;
        return false;
    }
References currentPlayerIndex, dummyIndex, and winningBidderIndex.
Referenced by CardUI.OnCardClicked(), and CardUI.OnMouseDown().
ChooseValidCard()
string GameManager.ChooseValidCard (List< string > hand) inline private
Wybiera poprawną kartę do zagrania przez AI, respektując prowadzony kolor.
Definition at line 314 of file GameManager.cs.
    {
        if (leadingSuit != null)
        {
            List<string> matchingSuit = hand.FindAll(card => card.StartsWith(leadingSuit));
            if (matchingSuit.Count > 0)
            {
                Debug.Log("AI wybiera kartę pasującą do koloru: " + leadingSuit);
                return matchingSuit[Random.Range(0, matchingSuit.Count)];
            }
        }
        Debug.Log("AI nie ma kart pasujących do koloru, wybiera losową kartę.");
        return hand[Random.Range(0, hand.Count)];
    }
References leadingSuit.
Referenced by PlayAICard().
ClearTable()
void GameManager.ClearTable () inline private
Czyści wszystkie karty ze stołu po zakończeniu lewy.
Definition at line 402 of file GameManager.cs.
    {
        isEndOfTurn= false;
        foreach (Transform child in tablePanel)
        {
            Destroy(child.gameObject);
        }
        Debug.Log("Stół został wyczyszczony.");
    }
References isEndOfTurn, and tablePanel.
Referenced by EvaluateTrickWinner().
DealCards()
void GameManager.DealCards () inline private
Tasuje i rozdaje karty graczom.
Definition at line 80 of file GameManager.cs.
    {
        List<string> deck = GenerateDeck();
        Shuffle(deck);
        playerHand = deck.GetRange(0, 13);
        topHand = deck.GetRange(13, 13);
        leftHand = deck.GetRange(26, 13);
        rightHand = deck.GetRange(39, 13);
        players[0].hand=playerHand;
        players[1].hand=leftHand;
        players[2].hand=topHand;
        players[3].hand=rightHand;
        playerHandDisplay.ShowHand(playerHand, true);
        topPlayerHandDisplay.ShowHand(topHand, false);
        leftPlayerHandDisplay.ShowHand(leftHand, false);
        rightPlayerHandDisplay.ShowHand(rightHand, false);
    }
References GenerateDeck(), leftHand, leftPlayerHandDisplay, playerHand, playerHandDisplay, players, rightHand, rightPlayerHandDisplay, Shuffle(), topHand, and topPlayerHandDisplay.
Referenced by ResetForNextDeal(), and Start().
EndBiddingEarly()
void GameManager.EndBiddingEarly () inline
Definition at line 640 of file GameManager.cs.
    {
        biddingInProgress = false;
        Debug.Log("Licytacja zakończona: 7NT");
    }
References biddingInProgress.
Referenced by BiddingUI.OnBidButtonClicked().
EndGame()
void GameManager.EndGame (int winningTeam, int winPoints, int losePoints) inline private
Definition at line 825 of file GameManager.cs.
    {
        Debug.Log($"KONIEC GRY! Zespół {winningTeam} wygrywa mecz.");
        endGamePanel.SetActive(true);
        endGameText.text = $"Team {(winningTeam == 0 ? "NS" : "EW")} won!\n +{(winPoints-losePoints)/100}";
    }
References endGamePanel.
Referenced by CalculateScore().
EndTurn()
void GameManager.EndTurn () inline
Obsługuje zakończenie jednej tury.
Definition at line 222 of file GameManager.cs.
    {
        int cardsOnTable = tablePanel.childCount;
        if(biddingInProgress) return;
        if (cardsOnTable >= 4)
        {
            leadingSuit = null;
            isEndOfTurn = true;
            StartCoroutine(EvaluateTrickWinner());
            Debug.Log("Prowadzący kolor został zresetowany");
            return;
        }
        currentTurn = (PlayerTurn)(((int)currentTurn + 1) % 4);
        currentPlayerIndex = (currentPlayerIndex + 1) % 4;
        Debug.Log("Tura kończy się. Teraz tura gracza: " + currentTurn);
        bool isDummyTurn = currentPlayerIndex == dummyIndex;
        bool isDeclarer = winningBidderIndex == 0;
        bool isHuman = currentPlayerIndex == 0;
        bool shouldAIPlay =
            players[currentPlayerIndex].IsAI ||
            (isDummyTurn && !isDeclarer) ||
            (isDummyTurn && isDeclarer && !isHuman);
        if (shouldAIPlay)
        {
            StartCoroutine(PlayAICard());
        }
    }
References biddingInProgress, currentPlayerIndex, currentTurn, dummyIndex, EvaluateTrickWinner(), isEndOfTurn, leadingSuit, PlayAICard(), players, tablePanel, and winningBidderIndex.
Referenced by CardUI.OnMouseDown(), PlayAICard(), and PlayCard().
EvaluateTrickWinner()
IEnumerator GameManager.EvaluateTrickWinner () inline private
Definition at line 435 of file GameManager.cs.
    {
        string leadSuit = currentTrick[0].cardID.Substring(0, 1);
        PlayedCard winningCard = currentTrick[0];
        int highestValue = GetCardValue(winningCard.cardID);
        string winningSuit = winningCard.cardID.Substring(0, 1);
        foreach (var played in currentTrick)
        {
            string suit = played.cardID.Substring(0, 1);
            int value = GetCardValue(played.cardID);
            bool playedIsTrump = (trumpSuit != null && suit == trumpSuit);
            bool winningIsTrump = (trumpSuit != null && winningSuit == trumpSuit);
            if (playedIsTrump && !winningIsTrump)
            {
                winningCard = played;
                winningSuit = suit;
                highestValue = value;
            }
            else if (suit == winningSuit && value > highestValue)
            {
                winningCard = played;
                highestValue = value;
            }
        }
        Debug.Log("Lewę wygrał gracz: " + winningCard.playerIndex);
        startingPlayerIndex = winningCard.playerIndex;
        tricksWonByPlayer[winningCard.playerIndex]++;
        currentPlayerIndex = startingPlayerIndex;
        currentTurn = (PlayerTurn)startingPlayerIndex;
        yield return new WaitForSeconds(2.0f);
        ClearTable();
        trickNumber++;
        leadingSuit = "";
        currentTrick.Clear();
        if (trickNumber >= 13)
        {
            Debug.Log("Wszystkie lewy rozegrane!");
            CalculateScore();
        }else{
            bool isDeclarer = (winningBidderIndex % 2 == 0);
            bool isDummy = currentPlayerIndex == dummyIndex;
            bool isDeclarerControllingDummy = isDummy && isDeclarer;
            bool isHumanPlaying = false;
            if(winningBidderIndex!=2){
                isHumanPlaying = (currentPlayerIndex == 0) || isDeclarerControllingDummy;
            }
            if (!isHumanPlaying)
            {
                StartCoroutine(PlayAICard());
            }
        }
    }
References CalculateScore(), GameManager.PlayedCard.cardID, ClearTable(), currentPlayerIndex, currentTrick, currentTurn, dummyIndex, GetCardValue(), leadingSuit, PlayAICard(), startingPlayerIndex, trickNumber, tricksWonByPlayer, trumpSuit, and winningBidderIndex.
Referenced by EndTurn().
GenerateDeck()
List< string > GameManager.GenerateDeck () inline private
Tworzy nową talię 52 kart.
Definition at line 103 of file GameManager.cs.
    {
        string[] suits = { "S", "H", "D", "C" };
        string[] values = { "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A" };
        List<string> deck = new List<string>();
        foreach (string suit in suits)
        {
            foreach (string value in values)
            {
                deck.Add(suit + value);
            }
        }
        return deck;
    }
Referenced by DealCards().
GetCardValue()
int GameManager.GetCardValue (string cardID) inline private
Definition at line 495 of file GameManager.cs.
    {
        string valuePart = cardID.Substring(1);
        switch (valuePart)
        {
            case "2": return 2;
            case "3": return 3;
            case "4": return 4;
            case "5": return 5;
            case "6": return 6;
            case "7": return 7;
            case "8": return 8;
            case "9": return 9;
            case "10": return 10;
            case "J": return 11;
            case "Q": return 12;
            case "K": return 13;
            case "A": return 14;
            default: return 0;
        }
    }
Referenced by EvaluateTrickWinner().
GetCurrentAIHand()
List< string > GameManager.GetCurrentAIHand () inline private
Zwraca rękę AI aktualnie wykonującego ruch.
Definition at line 333 of file GameManager.cs.
    {
        switch (currentTurn)
        {
            case PlayerTurn.Left: return leftHand;
            case PlayerTurn.Top: return topHand;
            case PlayerTurn.Right: return rightHand;
        }
        return null;
    }
References currentTurn, leftHand, rightHand, and topHand.
Referenced by PlayAICard().
GetPlayableHand()
List< string > GameManager.GetPlayableHand () inline private
Definition at line 789 of file GameManager.cs.
    {
        if (dummyIndex == 2)
        {
            topPlayerHandDisplay.ShowHand(topHand, true);
        }else if(dummyIndex == 1){
            leftPlayerHandDisplay.ShowHand(leftHand, true);
        }else if(dummyIndex == 3){
            rightPlayerHandDisplay.ShowHand(rightHand, true);
        }else if(dummyIndex == 0){
            playerHandDisplay.ShowHand(playerHand, true);
        }
        if (isPlayingDummy)
            return players[dummyIndex].hand;
        else
            return players[(int)currentTurn].hand;
    }
References currentTurn, dummyIndex, isPlayingDummy, leftHand, leftPlayerHandDisplay, playerHand, playerHandDisplay, players, rightHand, rightPlayerHandDisplay, topHand, and topPlayerHandDisplay.
Referenced by StartPlayPhase().
PlayAICard()
IEnumerator GameManager.PlayAICard () inline private
AI zagrywa kartę.
Definition at line 259 of file GameManager.cs.
    {
        if(isEndOfTurn){
            yield break;
        }
        string chosenCard;
        bool isDummyTurn = currentTurn == (PlayerTurn)dummyIndex;
        bool isDeclarerPlayingDummy = (currentPlayerIndex == dummyIndex) && (highestBidIndex == 0);
        List<string> handToCheck = isDeclarerPlayingDummy ? players[dummyIndex].hand : players[currentPlayerIndex].hand;
        if (isDeclarerPlayingDummy)
        {
            yield break;
        }
        else
        {
            isPlayingDummy = false;
        }
        if (currentPlayerIndex == dummyIndex && winningBidderIndex % 2 == 0 && winningBidderIndex==0)
        {
            yield break;
        }
        if (currentPlayerIndex == 0)
        {
            playerHandDisplay.ShowHand(handToCheck, true);
        }
        else if (currentPlayerIndex == dummyIndex && isDeclarerPlayingDummy)
        {
            topPlayerHandDisplay.ShowHand(handToCheck, true);
        }
        yield return new WaitForSeconds(1.0f);
        List<string> aiHand = GetCurrentAIHand();
        chosenCard = ChooseValidCard(handToCheck);
        handToCheck.Remove(chosenCard);
        SpawnCardOnTable(chosenCard,currentPlayerIndex);
        currentTrick.Add(new PlayedCard(chosenCard, currentPlayerIndex));
        if (string.IsNullOrEmpty(leadingSuit))
        {
            leadingSuit = chosenCard.Substring(0, 1);
            Debug.Log("Prowadzący kolor: " + leadingSuit);
        }
        UpdateAIHandDisplay();
        playerHandDisplay.ShowHand(playerHand, true);
        EndTurn();
    }
References ChooseValidCard(), currentPlayerIndex, currentTrick, currentTurn, dummyIndex, EndTurn(), GetCurrentAIHand(), highestBidIndex, isEndOfTurn, isPlayingDummy, leadingSuit, playerHand, playerHandDisplay, players, SpawnCardOnTable(), topPlayerHandDisplay, UpdateAIHandDisplay(), and winningBidderIndex.
Referenced by EndTurn(), EvaluateTrickWinner(), and StartPlayPhase().
PlayCard()
void GameManager.PlayCard (string cardID) inline
Gracz zagrywa kartę.
Definition at line 139 of file GameManager.cs.
    {
        if(!biddingInProgress){
        if(isEndOfTurn){
            return;
        }
        Debug.Log("Czy isEndOfTurn? " + isEndOfTurn);
        bool isDummyTurn = currentTurn == (PlayerTurn)dummyIndex;
        currentPlayerIndex = (int)currentTurn;
        bool isDeclarerPlayingDummy = (currentPlayerIndex == dummyIndex) && ((highestBidIndex + 2) % 4 == dummyIndex);
        List<string> handToCheck = isDeclarerPlayingDummy ? players[dummyIndex].hand : players[currentPlayerIndex].hand;
        if (!handToCheck.Contains(cardID))
        {
            Debug.LogWarning("Gracz nie ma tej karty!");
            return;
        }
        Debug.Log("Czy gracz ma kartę w ręku? " + handToCheck.Contains(cardID));
        if (!string.IsNullOrEmpty(leadingSuit))
        {
            bool hasSuit = handToCheck.Exists(card => card.StartsWith(leadingSuit));
            if (hasSuit && !cardID.StartsWith(leadingSuit))
            {
                Debug.LogWarning("Musisz zagrać kartę w prowadzonym kolorze: " + leadingSuit);
                return;
            }
        }
        handToCheck.Remove(cardID);
        bool removed= handToCheck.Remove(cardID);
        Debug.Log("Usunięto kartę z ręki: " + removed);
        if (currentPlayerIndex == 0)
        {
            playerHandDisplay.ShowHand(handToCheck, true);
        }
        else if (currentPlayerIndex == dummyIndex && isDeclarerPlayingDummy)
        {
            topPlayerHandDisplay.ShowHand(handToCheck, true);
        }
        int actualPlayerIndex = isDeclarerPlayingDummy ? dummyIndex : currentPlayerIndex;
        SpawnCardOnTable(cardID, actualPlayerIndex);
        currentTrick.Add(new PlayedCard(cardID, actualPlayerIndex));
        if (string.IsNullOrEmpty(leadingSuit))
        {
            leadingSuit = cardID.Substring(0, 1);
            Debug.Log("Prowadzący kolor: " + leadingSuit);
        }
        if (isDummyTurn && isDeclarerPlayingDummy)
        {
            currentTurn = (PlayerTurn)winningBidderIndex;
            isPlayingDummy = true;
        }
        else
        {
            isPlayingDummy = false;
        }
        UpdateAIHandDisplay();
        Debug.Log("Gracz zagrał: " + cardID);
        EndTurn();
        }
    }
References biddingInProgress, currentPlayerIndex, currentTrick, currentTurn, dummyIndex, EndTurn(), highestBidIndex, isEndOfTurn, isPlayingDummy, leadingSuit, playerHandDisplay, players, SpawnCardOnTable(), topPlayerHandDisplay, UpdateAIHandDisplay(), and winningBidderIndex.
Referenced by CardUI.OnCardClicked().
ResetForNextDeal()
void GameManager.ResetForNextDeal () inline private
Definition at line 806 of file GameManager.cs.
    {
        Debug.Log("Przygotowanie nowego rozdania...");
        DealCards();
        foreach (var player in players)
        {
            player.currentBid = "";
        }
        isEndOfTurn = false;
        leadingSuit = "";
        biddingHistory.Clear();
        highestBidIndex = -1;
        currentHighestBid = null;
        tricksWonByPlayer = new int[4];
        currentTrick.Clear();
        trickNumber = 0;
        startingBidderIndex= (startingBidderIndex + 1) % 4;
        StartCoroutine(StartBidding());
    }
References biddingHistory, currentHighestBid, currentTrick, DealCards(), highestBidIndex, isEndOfTurn, leadingSuit, players, StartBidding(), startingBidderIndex, trickNumber, and tricksWonByPlayer.
Referenced by CalculateScore(), and RestartGame().
RestartGame()
void GameManager.RestartGame () inline
Definition at line 831 of file GameManager.cs.
    {
        endGamePanel.SetActive(false);
        points= new int[2];
        pointsAboveLine = new int[2];
        pointsBelowLine = new int[2];
        partsWon = new int[2];
        UpdateScoreUI();
        ResetForNextDeal();
    }
References endGamePanel, partsWon, points, pointsAboveLine, pointsBelowLine, ResetForNextDeal(), and UpdateScoreUI().
ReturnToMainMenu()
void GameManager.ReturnToMainMenu () inline
Definition at line 842 of file GameManager.cs.
    {
        endGamePanel.SetActive(false);
        points= new int[2];
        pointsAboveLine = new int[2];
        pointsBelowLine = new int[2];
        partsWon = new int[2];
        UpdateScoreUI();
        SceneManager.LoadScene("StartScene");
    }
References endGamePanel, partsWon, points, pointsAboveLine, pointsBelowLine, and UpdateScoreUI().
Shuffle()
void GameManager.Shuffle (List< string > list) inline private
Tasuje listę kart.
Definition at line 124 of file GameManager.cs.
    {
        for (int i = 0; i < list.Count; i++)
        {
            int rnd = Random.Range(i, list.Count);
            var temp = list[i];
            list[i] = list[rnd];
            list[rnd] = temp;
        }
    }
Referenced by DealCards().
SpawnCardOnTable()
void GameManager.SpawnCardOnTable (string cardID, int playerIndex) inline private
Pozwala wystawić kartę na stole.
Definition at line 348 of file GameManager.cs.
    {
        GameObject card = Instantiate(playerHandDisplay.cardPrefab, tablePanel);
        card.GetComponent<CardUI>().cardID = cardID;
        Image image = card.GetComponent<Image>();
        if (playerHandDisplay.cardSpriteDict.ContainsKey(cardID))
        {
            image.sprite = playerHandDisplay.cardSpriteDict[cardID];
        }
        else
        {
            Debug.LogWarning("Brak sprite'a dla karty: " + cardID);
        }
        Debug.Log("Spawnuję kartę: " + cardID + " od gracza: " + playerIndex);
        Vector2 position = Vector2.zero;
        PlayerTurn turn = (PlayerTurn)playerIndex;
        switch (turn)
        {
            case PlayerTurn.Bottom: position = new Vector2(-35, -70); break;
            case PlayerTurn.Top: position = new Vector2(-35, 70); break;
            case PlayerTurn.Left: position = new Vector2(-250, 0); break;
            case PlayerTurn.Right: position = new Vector2(200, 0); break;
        }
        card.GetComponent<RectTransform>().anchoredPosition = position;
    }
References playerHandDisplay, and tablePanel.
Referenced by PlayAICard(), and PlayCard().
Start()
void GameManager.Start () inline private
Definition at line 56 of file GameManager.cs.
    {
        endGamePanel.SetActive(false);
        players = new List<Player>
        {
            new Player("Player", false),
            new Player("Left Player", true),
            new Player("Top Player", true),
            new Player("Right Player", true)
        };
        playerHandDisplay.LoadCardSprites();
        topPlayerHandDisplay.LoadCardSprites();
        leftPlayerHandDisplay.LoadCardSprites();
        rightPlayerHandDisplay.LoadCardSprites();
        DealCards();
        StartCoroutine(StartBidding());
    }
References DealCards(), endGamePanel, leftPlayerHandDisplay, playerHandDisplay, players, rightPlayerHandDisplay, StartBidding(), and topPlayerHandDisplay.
StartBidding()
IEnumerator GameManager.StartBidding () inline private
Definition at line 545 of file GameManager.cs.
    {
        biddingInProgress = true;
        Debug.Log("Licytacja rozpoczęta.");
        int bidderIndex = startingBidderIndex;
        int passesInARow=0;
        while (biddingInProgress)
        {
            Player currentPlayer = players[bidderIndex];
            string bid = "";
            if (bidderIndex == 0)
            {
                BiddingUI.Instance.ShowBiddingPanel(currentHighestBid);
                yield return new WaitUntil(() => !string.IsNullOrEmpty(BiddingUI.Instance.GetSelectedBid()));
                bid = BiddingUI.Instance.GetSelectedBid();
                if (BiddingUI.Instance.currentBidText != null)
                {
                    BiddingUI.Instance.currentBidText.text = $"{currentPlayer.name}: {bid}";
                }
                yield return new WaitForSeconds(1.5f);
                if (bid=="Pas"){
                    passesInARow++;
                    Debug.Log($"Passes in a row{passesInARow}");
                    if (passesInARow >= 3 && currentHighestBid != "")
                    {
                        biddingInProgress = false;
                        StartPlayPhase();
                        break;
                    }
                }else{
                    currentHighestBid = bid;
                    passesInARow = 0;
                    Debug.Log($"Passes in a row{passesInARow}");
                    if (bid == "7NT")
                    {
                        biddingInProgress = false;
                        winningBidderIndex = bidderIndex;
                        StartPlayPhase();
                        break;
                    }
                }
            }
            else
            {
                yield return new WaitForSeconds(1f);
                bid = currentPlayer.MakeBid();
                if (BiddingUI.Instance.currentBidText != null)
                {
                    BiddingUI.Instance.currentBidText.text = $"{currentPlayer.name}: {bid}";
                }
                yield return new WaitForSeconds(1.5f);
                if(bid=="Pas"){
                    passesInARow++;
                    Debug.Log($"Passes in a row{passesInARow}");
                    if (passesInARow >= 3 && currentHighestBid != "")
                    {
                        biddingInProgress = false;
                        StartPlayPhase();
                        break;
                    }
                }else{
                    currentHighestBid = bid;
                    passesInARow = 0;
                    Debug.Log($"Passes in a row{passesInARow}");
                    if (bid == "7NT")
                    {
                        biddingInProgress = false;
                        winningBidderIndex = bidderIndex;
                        StartPlayPhase();
                        break;
                    }
                 }
            }
            Debug.Log($"{bid}");
            currentPlayer.currentBid = bid;
            biddingHistory.Add(new Bid(currentPlayer.name, bid));
            int bidIndex = System.Array.IndexOf(possibleCalls, bid);
            if (bid != "Pas" && bidIndex > highestBidIndex)
            {
                highestBidIndex = bidIndex;
                winningBidderIndex= bidderIndex;
            }
            bidderIndex = (bidderIndex + 1) % players.Count;
        }
        biddingInProgress = false;
        Debug.Log("Licytacja zakończona.");
    }
References biddingHistory, biddingInProgress, BiddingUI.currentBidText, currentHighestBid, BiddingUI.GetSelectedBid(), highestBidIndex, BiddingUI.Instance, Player.MakeBid(), Player.name, players, possibleCalls, BiddingUI.ShowBiddingPanel(), startingBidderIndex, StartPlayPhase(), and winningBidderIndex.
Referenced by ResetForNextDeal(), and Start().
StartPlayPhase()
void GameManager.StartPlayPhase () inline private
Definition at line 646 of file GameManager.cs.
    {
        isEndOfTurn = false;
        leadingSuit = "";
        trickNumber = 0;
        currentTrick.Clear();
        dummyIndex = (winningBidderIndex + 2) % 4;
        GetPlayableHand();
        Debug.Log("Faza rozgrywki rozpoczęta.");
        string winnerBidName= players[winningBidderIndex].name;
        BiddingUI.Instance.currentBidText.text = $"{winnerBidName}: {currentHighestBid}";
        string suitSymbol = currentHighestBid.Substring(1).ToUpper();
        trumpSuit = suitSymbol == "NT" ? null : suitSymbol;
        currentPlayerIndex = (winningBidderIndex + 1) % 4;
        currentTurn = (PlayerTurn)currentPlayerIndex;
        if (players[currentPlayerIndex].IsAI ||
            (currentTurn == (PlayerTurn)dummyIndex && currentPlayerIndex == winningBidderIndex))
        {
            StartCoroutine(PlayAICard());
        }
        else
        {
            Debug.Log("Czeka na ruch gracza: " + players[currentPlayerIndex].name);
        }
    }
References currentHighestBid, currentPlayerIndex, currentTrick, currentTurn, dummyIndex, GetPlayableHand(), isEndOfTurn, leadingSuit, PlayAICard(), players, trickNumber, trumpSuit, and winningBidderIndex.
Referenced by StartBidding().
UpdateAIHandDisplay()
void GameManager.UpdateAIHandDisplay () inline private
Definition at line 377 of file GameManager.cs.
    {
        if(dummyIndex==1){
            leftPlayerHandDisplay.ShowHand(leftHand, true);
            topPlayerHandDisplay.ShowHand(topHand, false);
            rightPlayerHandDisplay.ShowHand(rightHand, false);
        }else if(dummyIndex==2){
            topPlayerHandDisplay.ShowHand(topHand, true);
            leftPlayerHandDisplay.ShowHand(leftHand, false);
            rightPlayerHandDisplay.ShowHand(rightHand, false);
        }else if(dummyIndex==3){
            rightPlayerHandDisplay.ShowHand(rightHand, true);
            topPlayerHandDisplay.ShowHand(topHand, false);
            leftPlayerHandDisplay.ShowHand(leftHand, false);
        }else{
            topPlayerHandDisplay.ShowHand(topHand, false);
            leftPlayerHandDisplay.ShowHand(leftHand, false);
            rightPlayerHandDisplay.ShowHand(rightHand, false);
        }
    }
References dummyIndex, leftHand, leftPlayerHandDisplay, rightHand, rightPlayerHandDisplay, topHand, and topPlayerHandDisplay.
Referenced by PlayAICard(), and PlayCard().
UpdateScoreUI()
void GameManager.UpdateScoreUI () inline private
Definition at line 778 of file GameManager.cs.
    {
        Debug.Log("UpdateScoreUI called");
        if (pointsBelowText != null)
            pointsBelowText.text = $"NS: {pointsBelowLine[0]}   EW: {pointsBelowLine[1]}";
        if (pointsAboveText != null)
            pointsAboveText.text = $"NS: {pointsAboveLine[0]}  EW: {pointsAboveLine[1]}";
    }
References pointsAboveText, and pointsBelowText.
Referenced by CalculateScore(), RestartGame(), and ReturnToMainMenu().
Member Data Documentation
biddingHistory
List<Bid> GameManager.biddingHistory = new List<Bid>()
Definition at line 529 of file GameManager.cs.
Referenced by ResetForNextDeal(), and StartBidding().
biddingInProgress
bool GameManager.biddingInProgress = false private
Definition at line 542 of file GameManager.cs.
Referenced by EndBiddingEarly(), EndTurn(), PlayCard(), and StartBidding().
cardPrefab
GameObject GameManager.cardPrefab
Definition at line 21 of file GameManager.cs.
currentHighestBid
string GameManager.currentHighestBid =null private
Definition at line 541 of file GameManager.cs.
Referenced by CalculateScore(), ResetForNextDeal(), StartBidding(), and StartPlayPhase().
currentPlayerIndex
int GameManager.currentPlayerIndex = 0
Definition at line 42 of file GameManager.cs.
Referenced by CanPlayCard(), EndTurn(), EvaluateTrickWinner(), PlayAICard(), PlayCard(), and StartPlayPhase().
currentTrick
List<PlayedCard> GameManager.currentTrick = new List<PlayedCard>()
Definition at line 40 of file GameManager.cs.
Referenced by EvaluateTrickWinner(), PlayAICard(), PlayCard(), ResetForNextDeal(), and StartPlayPhase().
currentTurn
PlayerTurn GameManager.currentTurn = PlayerTurn.Bottom
Definition at line 36 of file GameManager.cs.
Referenced by EndTurn(), EvaluateTrickWinner(), GetCurrentAIHand(), GetPlayableHand(), PlayAICard(), PlayCard(), and StartPlayPhase().
dummyIndex
int GameManager.dummyIndex = -1
Definition at line 788 of file GameManager.cs.
Referenced by CanPlayCard(), EndTurn(), EvaluateTrickWinner(), GetPlayableHand(), CardUI.OnCardClicked(), PlayAICard(), PlayCard(), StartPlayPhase(), and UpdateAIHandDisplay().
endGamePanel
GameObject GameManager.endGamePanel
Definition at line 23 of file GameManager.cs.
Referenced by EndGame(), RestartGame(), ReturnToMainMenu(), and Start().
endGameText
TextMeshProUGUI GameManager.endGameText
Definition at line 24 of file GameManager.cs.
highestBidIndex
int GameManager.highestBidIndex = -1
Definition at line 540 of file GameManager.cs.
Referenced by Player.MakeBid(), PlayAICard(), PlayCard(), ResetForNextDeal(), and StartBidding().
Instance
GameManager GameManager.Instance static
Definition at line 14 of file GameManager.cs.
Referenced by Awake(), Player.MakeBid(), BiddingUI.OnBidButtonClicked(), CardUI.OnCardClicked(), and CardUI.OnMouseDown().
isEndOfTurn
bool GameManager.isEndOfTurn = false private
Definition at line 44 of file GameManager.cs.
Referenced by ClearTable(), EndTurn(), PlayAICard(), PlayCard(), ResetForNextDeal(), and StartPlayPhase().
isPlayingDummy
bool GameManager.isPlayingDummy = false private
Definition at line 787 of file GameManager.cs.
Referenced by GetPlayableHand(), PlayAICard(), and PlayCard().
leadingSuit
string GameManager.leadingSuit = null
Definition at line 38 of file GameManager.cs.
Referenced by ChooseValidCard(), EndTurn(), EvaluateTrickWinner(), CardUI.OnMouseDown(), PlayAICard(), PlayCard(), ResetForNextDeal(), and StartPlayPhase().
leftHand
List<string> GameManager.leftHand = new List<string>()
Definition at line 32 of file GameManager.cs.
Referenced by DealCards(), GetCurrentAIHand(), GetPlayableHand(), and UpdateAIHandDisplay().
leftPlayerHandDisplay
HandDisplay GameManager.leftPlayerHandDisplay
Definition at line 20 of file GameManager.cs.
Referenced by DealCards(), GetPlayableHand(), Start(), and UpdateAIHandDisplay().
partsWon
int [] GameManager.partsWon = new int[2] private
Definition at line 47 of file GameManager.cs.
Referenced by CalculateScore(), RestartGame(), and ReturnToMainMenu().
playerHand
List<string> GameManager.playerHand = new List<string>()
Listy kart posiadanych przez graczy.
Definition at line 30 of file GameManager.cs.
Referenced by DealCards(), GetPlayableHand(), CardUI.OnMouseDown(), and PlayAICard().
playerHandDisplay
HandDisplay GameManager.playerHandDisplay
Wyświetlacze rąk gracza i AI.
Definition at line 20 of file GameManager.cs.
Referenced by DealCards(), GetPlayableHand(), CardUI.OnMouseDown(), PlayAICard(), PlayCard(), SpawnCardOnTable(), and Start().
players
List<Player> GameManager.players = new List<Player>()
Definition at line 45 of file GameManager.cs.
Referenced by DealCards(), EndTurn(), GetPlayableHand(), CardUI.OnCardClicked(), PlayAICard(), PlayCard(), ResetForNextDeal(), Start(), StartBidding(), and StartPlayPhase().
points
int [] GameManager.points = new int[2] private
Definition at line 677 of file GameManager.cs.
Referenced by CalculateScore(), RestartGame(), and ReturnToMainMenu().
pointsAboveLine
int [] GameManager.pointsAboveLine = new int[2] private
Definition at line 676 of file GameManager.cs.
Referenced by CalculateScore(), RestartGame(), and ReturnToMainMenu().
pointsAboveText
TextMeshProUGUI GameManager.pointsAboveText
Definition at line 679 of file GameManager.cs.
Referenced by UpdateScoreUI().
pointsBelowLine
int [] GameManager.pointsBelowLine = new int[2] private
Definition at line 675 of file GameManager.cs.
Referenced by CalculateScore(), RestartGame(), and ReturnToMainMenu().
pointsBelowText
TextMeshProUGUI GameManager.pointsBelowText
Definition at line 678 of file GameManager.cs.
Referenced by UpdateScoreUI().
possibleCalls
string [] GameManager.possibleCalls
Initial value:
= {
        "1♣", "1♦", "1♥", "1♠", "1NT",
        "2♣", "2♦", "2♥", "2♠", "2NT",
        "3♣", "3♦", "3♥", "3♠", "3NT",
        "4♣", "4♦", "4♥", "4♠", "4NT",
        "5♣", "5♦", "5♥", "5♠", "5NT",
        "6♣", "6♦", "6♥", "6♠", "6NT",
        "7♣", "7♦", "7♥", "7♠", "7NT"
    }
Definition at line 530 of file GameManager.cs.
{
        "1♣", "1♦", "1♥", "1♠", "1NT",
        "2♣", "2♦", "2♥", "2♠", "2NT",
        "3♣", "3♦", "3♥", "3♠", "3NT",
        "4♣", "4♦", "4♥", "4♠", "4NT",
        "5♣", "5♦", "5♥", "5♠", "5NT",
        "6♣", "6♦", "6♥", "6♠", "6NT",
        "7♣", "7♦", "7♥", "7♠", "7NT"
    };
Referenced by Player.MakeBid(), and StartBidding().
rightHand
List<string> GameManager.rightHand = new List<string>()
Definition at line 33 of file GameManager.cs.
Referenced by DealCards(), GetCurrentAIHand(), GetPlayableHand(), and UpdateAIHandDisplay().
rightPlayerHandDisplay
HandDisplay GameManager.rightPlayerHandDisplay
Definition at line 20 of file GameManager.cs.
Referenced by DealCards(), GetPlayableHand(), Start(), and UpdateAIHandDisplay().
startingBidderIndex
int GameManager.startingBidderIndex = 0 private
Definition at line 544 of file GameManager.cs.
Referenced by ResetForNextDeal(), and StartBidding().
startingPlayerIndex
int GameManager.startingPlayerIndex = 0
Definition at line 41 of file GameManager.cs.
Referenced by EvaluateTrickWinner().
tablePanel
Transform GameManager.tablePanel
Definition at line 22 of file GameManager.cs.
Referenced by ClearTable(), EndTurn(), CardUI.OnMouseDown(), and SpawnCardOnTable().
topHand
List<string> GameManager.topHand = new List<string>()
Definition at line 31 of file GameManager.cs.
Referenced by DealCards(), GetCurrentAIHand(), GetPlayableHand(), and UpdateAIHandDisplay().
topPlayerHandDisplay
HandDisplay GameManager.topPlayerHandDisplay
Definition at line 20 of file GameManager.cs.
Referenced by DealCards(), GetPlayableHand(), PlayAICard(), PlayCard(), Start(), and UpdateAIHandDisplay().
trickNumber
int GameManager.trickNumber =0 private
Ocenia zwycięzcę lewy i przygotowuje następną turę.
Definition at line 434 of file GameManager.cs.
Referenced by EvaluateTrickWinner(), ResetForNextDeal(), and StartPlayPhase().
tricksWonByPlayer
int [] GameManager.tricksWonByPlayer = new int[4] private
Definition at line 674 of file GameManager.cs.
Referenced by CalculateScore(), EvaluateTrickWinner(), and ResetForNextDeal().
trumpSuit
string GameManager.trumpSuit = null private
Definition at line 543 of file GameManager.cs.
Referenced by EvaluateTrickWinner(), and StartPlayPhase().
winningBidderIndex
int GameManager.winningBidderIndex = -1 private
Definition at line 46 of file GameManager.cs.
Referenced by CalculateScore(), CanPlayCard(), EndTurn(), EvaluateTrickWinner(), PlayAICard(), PlayCard(), StartBidding(), and StartPlayPhase().
The documentation for this class was generated from the following file:
Assets/Scripts/GameManager.cs