PI2025- Bridge: BiddingUI Class Reference
BiddingUI Class Reference
Obsługuje interfejs użytkownika licytacji: wyświetlanie przycisków i wybór oferty.
Public Member Functions
void ShowBiddingPanel (string highestBid)
Pokazuje panel licytacji i ustawia dostępne oferty.
void OnBidButtonClicked (string bid)
Obsługuje kliknięcie przycisku licytacji i zapisuje wybór.
string GetSelectedBid ()
Zwraca aktualnie wybraną licytację.
Public Attributes
GameObject panel
TMP_Text currentBidText
GameObject bidButtonPrefab
Transform buttonContainer
Static Public Attributes
static BiddingUI Instance
Private Member Functions
void Awake ()
void Start ()
void AddBiddingButtons ()
Tworzy dynamicznie wszystkie przyciski licytacji.
void UpdateBidButtons ()
Aktualizuje przyciski licytacyjne na podstawie aktualnej najwyższej licytacji.
bool IsBidHigher (string newBid, string currentBid)
Sprawdza, czy nowa licytacja jest wyższa niż poprzednia.
Private Attributes
string selectedBid = ""
List< GameObject > bidButtons = new List<GameObject>()
string currentHighestBid = ""
Detailed Description
Obsługuje interfejs użytkownika licytacji: wyświetlanie przycisków i wybór oferty.
Definition at line 10 of file BiddingUI.cs.
Member Function Documentation
AddBiddingButtons()
void BiddingUI.AddBiddingButtons () inline private
Tworzy dynamicznie wszystkie przyciski licytacji.
Definition at line 35 of file BiddingUI.cs.
    {
        string[] suits = { "C", "D", "H", "S", "NT" };
        for (int level = 1; level <= 7; level++)
        {
            foreach (string suit in suits)
            {
                string bid = level + suit;
                GameObject newButton = Instantiate(bidButtonPrefab, buttonContainer);
                Button button = newButton.GetComponent<Button>();
                TMP_Text buttonText = newButton.GetComponentInChildren<TMP_Text>();
                buttonText.text = bid;
                button.onClick.AddListener(() => OnBidButtonClicked(bid));
                bidButtons.Add(newButton);
            }
        }
        // Dodaj osobny przycisk "Pass"
        GameObject passButton = Instantiate(bidButtonPrefab, buttonContainer);
        Button passBtn = passButton.GetComponent<Button>();
        TMP_Text passText = passButton.GetComponentInChildren<TMP_Text>();
        passText.text = "Pas";
        passBtn.onClick.AddListener(() => OnBidButtonClicked("Pas"));
        bidButtons.Add(passButton);
    }
References bidButtonPrefab, bidButtons, buttonContainer, and OnBidButtonClicked().
Referenced by Start().
Awake()
void BiddingUI.Awake () inline private
Definition at line 21 of file BiddingUI.cs.
    {
        Instance = this;
        panel.SetActive(false);
    }
References Instance, and panel.
GetSelectedBid()
string BiddingUI.GetSelectedBid () inline
Zwraca aktualnie wybraną licytację.
Definition at line 95 of file BiddingUI.cs.
    {
        return selectedBid;
    }
References selectedBid.
Referenced by GameManager.StartBidding().
IsBidHigher()
bool BiddingUI.IsBidHigher (string newBid, string currentBid) inline private
Sprawdza, czy nowa licytacja jest wyższa niż poprzednia.
Parameters
newBid Nowa oferta
currentBid Aktualna najwyższa
Returns
Czy nowa jest wyższa
Definition at line 127 of file BiddingUI.cs.
    {
        if (newBid == "Pas" || string.IsNullOrEmpty(newBid)) return false;
        if (string.IsNullOrEmpty(currentBid)) return true;
        int GetBidValue(string bid)
        {
            if (bid == "Pas") return -1;
            string[] suits = { "C", "D", "H", "S", "NT" };
            int level = int.Parse(bid[0].ToString());
            string suit = bid.Substring(1);
            int suitValue = System.Array.IndexOf(suits, suit);
            return level * 5 + suitValue;
        }
        return GetBidValue(newBid) > GetBidValue(currentBid);
    }
Referenced by UpdateBidButtons().
OnBidButtonClicked()
void BiddingUI.OnBidButtonClicked (string bid) inline
Obsługuje kliknięcie przycisku licytacji i zapisuje wybór.
Parameters
bid Licytacja wybrana przez gracza
Definition at line 81 of file BiddingUI.cs.
    {
        selectedBid = bid;
        panel.SetActive(false);
        if (bid == "7NT")
        {
            GameManager.Instance.EndBiddingEarly(); // Tę metodę musisz dopisać
        }
    }
References GameManager.EndBiddingEarly(), GameManager.Instance, panel, and selectedBid.
Referenced by AddBiddingButtons().
ShowBiddingPanel()
void BiddingUI.ShowBiddingPanel (string highestBid) inline
Pokazuje panel licytacji i ustawia dostępne oferty.
Parameters
highestBid Aktualnie najwyższa licytacja
Definition at line 66 of file BiddingUI.cs.
    {
        selectedBid = "";
        currentHighestBid = highestBid;
        panel.SetActive(true);
        UpdateBidButtons();
        // Ustawienie początkowego tekstu
        if (currentBidText != null)
            currentBidText.text = (highestBid == "" ? "brak" : "Highest bid: "+highestBid);
    }
References currentBidText, currentHighestBid, panel, selectedBid, and UpdateBidButtons().
Referenced by GameManager.StartBidding().
Start()
void BiddingUI.Start () inline private
Definition at line 27 of file BiddingUI.cs.
    {
        AddBiddingButtons();
    }
References AddBiddingButtons().
UpdateBidButtons()
void BiddingUI.UpdateBidButtons () inline private
Aktualizuje przyciski licytacyjne na podstawie aktualnej najwyższej licytacji.
Definition at line 103 of file BiddingUI.cs.
    {
        foreach (var btn in bidButtons)
        {
            TMP_Text btnText = btn.GetComponentInChildren<TMP_Text>();
            string bid = btnText.text;
            if (bid == "Pas")
            {
                btn.SetActive(true);
                continue;
            }
            bool isLegal = IsBidHigher(bid, currentHighestBid);
            btn.SetActive(isLegal);
        }
    }
References bidButtons, currentHighestBid, and IsBidHigher().
Referenced by ShowBiddingPanel().
Member Data Documentation
bidButtonPrefab
GameObject BiddingUI.bidButtonPrefab
Definition at line 16 of file BiddingUI.cs.
Referenced by AddBiddingButtons().
bidButtons
List<GameObject> BiddingUI.bidButtons = new List<GameObject>() private
Definition at line 18 of file BiddingUI.cs.
Referenced by AddBiddingButtons(), and UpdateBidButtons().
buttonContainer
Transform BiddingUI.buttonContainer
Definition at line 17 of file BiddingUI.cs.
Referenced by AddBiddingButtons().
currentBidText
TMP_Text BiddingUI.currentBidText
Definition at line 15 of file BiddingUI.cs.
Referenced by ShowBiddingPanel(), and GameManager.StartBidding().
currentHighestBid
string BiddingUI.currentHighestBid = "" private
Definition at line 19 of file BiddingUI.cs.
Referenced by ShowBiddingPanel(), and UpdateBidButtons().
Instance
BiddingUI BiddingUI.Instance static
Definition at line 12 of file BiddingUI.cs.
Referenced by Awake(), and GameManager.StartBidding().
panel
GameObject BiddingUI.panel
Definition at line 13 of file BiddingUI.cs.
Referenced by Awake(), OnBidButtonClicked(), and ShowBiddingPanel().
selectedBid
string BiddingUI.selectedBid = "" private
Definition at line 14 of file BiddingUI.cs.
Referenced by GetSelectedBid(), OnBidButtonClicked(), and ShowBiddingPanel().
The documentation for this class was generated from the following file:
Assets/Scripts/BiddingUI.cs