PI2025- Bridge: MultiplayerCardUI Class Reference
MultiplayerCardUI Class Reference
UI reprezentujące kartę w trybie multiplayer. Obsługuje kliknięcie, wyrzucanie i synchronizację stanu.
Public Member Functions
void InitCard (Sprite sprite, string id)
void SetFaceUp (bool faceUp)
void OnCardClicked ()
Public Attributes
Image cardImage
string cardID
Sprite backSprite
Sprite frontSprite
Private Member Functions
void Start ()
Detailed Description
UI reprezentujące kartę w trybie multiplayer. Obsługuje kliknięcie, wyrzucanie i synchronizację stanu.
Definition at line 9 of file MultiplayerCardUI.cs.
Member Function Documentation
InitCard()
void MultiplayerCardUI.InitCard (Sprite sprite, string id) inline
Definition at line 23 of file MultiplayerCardUI.cs.
    {
        frontSprite = sprite;
        cardImage.sprite = sprite;
        cardID = id;
    }
References cardID, and frontSprite.
OnCardClicked()
void MultiplayerCardUI.OnCardClicked () inline
Definition at line 35 of file MultiplayerCardUI.cs.
    {
        if (!MultiplayerGameManager.Instance.CanPlayCard())
        {
            Debug.Log("Nie twoja tura");
            return;
        }
        var allPlayers = FindObjectsOfType<NetworkPlayer>();
        var localPlayer = allPlayers.FirstOrDefault(p => p.isLocalPlayer);
        if (localPlayer == null)
        {
            Debug.LogWarning("Nie znaleziono lokalnego gracza!");
            return;
        }
        var gm = MultiplayerGameManager.Instance;
        if(gm.currentPlayerIndex== gm.dummyIndex && localPlayer.playerIndex!= gm.winningBidderIndex){
            Debug.Log("Tylko wygrany licytacji moze grac za dummiego");
            return;
        }
        Debug.Log($"[{localPlayer.playerIndex}] Wysyłam CmdPlayCard({cardID})");
        localPlayer.CmdPlayCard(cardID);
    }
References MultiplayerGameManager.CanPlayCard(), cardID, MultiplayerGameManager.CmdPlayCard(), and MultiplayerGameManager.Instance.
Referenced by Start().
SetFaceUp()
void MultiplayerCardUI.SetFaceUp (bool faceUp) inline
Definition at line 30 of file MultiplayerCardUI.cs.
    {
        cardImage.sprite = faceUp ? frontSprite : backSprite;
    }
References backSprite, and frontSprite.
Start()
void MultiplayerCardUI.Start () inline private
Definition at line 16 of file MultiplayerCardUI.cs.
    {
        var button = GetComponent<Button>();
        if (button != null)
            button.onClick.AddListener(OnCardClicked);
    }
References OnCardClicked().
Member Data Documentation
backSprite
Sprite MultiplayerCardUI.backSprite
Definition at line 13 of file MultiplayerCardUI.cs.
Referenced by SetFaceUp().
cardID
string MultiplayerCardUI.cardID
Definition at line 12 of file MultiplayerCardUI.cs.
Referenced by InitCard(), OnCardClicked(), and MultiplayerGameManager.RpcSpawnCardOnTable().
cardImage
Image MultiplayerCardUI.cardImage
Definition at line 11 of file MultiplayerCardUI.cs.
frontSprite
Sprite MultiplayerCardUI.frontSprite
Definition at line 14 of file MultiplayerCardUI.cs.
Referenced by InitCard(), and SetFaceUp().
The documentation for this class was generated from the following file:
Assets/Scripts/MultiplayerCardUI.cs